### ISSUE TITLE
Remove dependency on MFC..

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Falcor#1]
Hi,
trying to compile Falcor 2.0 on Windows with VS2017 community.. I don't have MFC so I get errors like:
not found #include <atlstr.h>
in MonitorInfo.h
commenting it and adding #include <Windows.h> to monitorinfo.cpp seems clear it's using only for CString class which seems overkill..
so can remove tan dependency using std::string for example..
should help with posible portability to Linux also..
thanks..

**Comment by nbenty** [comment]
Thanks for pointing that out. That was an oversight, I'll fix it.

**Comment by nbenty** [comment]
@kyaoNV Please fix it
