### ISSUE TITLE
d3d12 error with two render context

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#102]
I created two render context (later with multithread) and want to blend the rendertarget of mpSecondRenderContext onto the rendertarget of mpRenderContext. I used two resource barrier for the rendertarget of mpSecondRenderContext

```
		render(); //record two commandlist for mpSecondRenderContext and mpRenderContext
		mpSecondRenderContext->resourceBarrier(mpSecondRenderContext->getGraphicsState()->getFbo()->getColorTexture(0).get(), Falcor::FResource::State::ShaderResource);

		//blend the rendertarget of mpSecondRenderContext onto the rendertarget of mpRenderContext
		mpRenderContext->blit(mpSecondRenderContext->getGraphicsState()->getFbo()->getColorTexture(0)->getSRV(), mpRenderContext->getGraphicsState()->getFbo()->getColorTexture(0)->getRTV());

		app->device->getSecondRenderContext()->resourceBarrier(mpSecondRenderContext->getGraphicsState()->getFbo()->getColorTexture(0).get(), Falcor::FResource::State::RenderTarget);

		mpRenderContext->blit(mpRenderContext->getGraphicsState()->getFbo()->getColorTexture(0)->getSRV(), mpBackBufferFBO->getColorTexture(0)->getRTV());
```
the code in Device::Present() looks like:
```
    void Device::present()
    {
		if (mpSecondRenderContext->getGraphicsState())
		{
			mpSecondRenderContext->flush();
		}
		
		mpRenderContext->resourceBarrier(mpSwapChainFbos[mCurrentBackBufferIndex]->getColorTexture(0).get(), FResource::State::Present);
        mpRenderContext->flush();

        apiPresent();
        mpFrameFence->gpuSignal(mpRenderContext->getLowLevelData()->getCommandQueue());

		if (mpSecondRenderContext->getGraphicsState())
		mpFrameFence->gpuSignal(mpSecondRenderContext->getLowLevelData()->getCommandQueue());
```
the program runs like before, but I got errors for the first frame, and after that the errors disappeared:

> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Non-simultaneous-access Texture Resource (0x000002ABD7D322F0:'Unnamed Object') is still referenced by transition_barrier GPU operations in-flight on another Command Queue (0x000002AB37E4FE20:'Unnamed ID3D12CommandQueue Object'). It is not safe to start write|transition_barrier GPU operations now on this Command Queue (0x000002AB2D82C210:'Unnamed ID3D12CommandQueue Object'). This can result in race conditions and application instability. [ EXECUTION ERROR #1047: OBJECT_ACCESSED_WHILE_STILL_IN_USE]
> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x000002AB37DCE160:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x000002ABD7D322F0:'Unnamed ID3D12Resource Object') (subresource: 0) specified by transition barrier does not match with the state (0x80: D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) specified in the previous call to ResourceBarrier [ RESOURCE_MANIPULATION ERROR #527: RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH]
> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x000002AB37DCE160:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x000002ABE1E3A1A0:'Unnamed ID3D12Resource Object') (subresource: 0) specified by transition barrier does not match with the state (0x80: D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) specified in the previous call to ResourceBarrier [ RESOURCE_MANIPULATION ERROR #527: RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH]
> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x000002AB37DCE160:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x000002ABE1E345A0:'Unnamed ID3D12Resource Object') (subresource: 0) specified by transition barrier does not match with the state (0x80: D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) specified in the previous call to ResourceBarrier [ RESOURCE_MANIPULATION ERROR #527: RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH]

**Comment by bryan05** [comment]
thanks nbenty, the same CommandQueueHandle worked. But another error occur when the second render contex  runs every 3 frame and the program crashes at mDeferredReleases.pop();. 
```
    void Device::executeDeferredReleases()
    {
        mpResourceAllocator->executeDeferredReleases();
        uint64_t gpuVal = mpFrameFence->getGpuValue();
        while (mDeferredReleases.size() && mDeferredReleases.front().frameID <= gpuVal)
        {
            **mDeferredReleases.pop();** ///crash at this row
        }
        mpCpuDescPool->executeDeferredReleases();
        mpGpuDescPool->executeDeferredReleases();
    }
```
the error is 

> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: An ID3D12Resource object (0x0000022EFECAA9F0:'Unnamed Object') referenced in a command list (0x0000022E5F546C50:'Unnamed ID3D12GraphicsCommandList Object') was deleted prior to executing the command list.  This is invalid and can result in application instability. [ EXECUTION ERROR #921: OBJECT_DELETED_WHILE_STILL_IN_USE]
> D3D12 ERROR: ID3D12Resource1::<final-release>: CORRUPTION: An ID3D12Resource object (0x0000022E0B34ADF0:'Unnamed Object') is referenced by GPU operations in-flight on Command Queue (0x0000022E54F26C00:'Unnamed ID3D12CommandQueue Object').  It is not safe to final-release objects that may have GPU operations pending.  This can result in application instability. [ EXECUTION ERROR #921: OBJECT_DELETED_WHILE_STILL_IN_USE]
when the second render contex runs every frame, it's fine, no error

**Comment by bryan05** [comment]
the second context is run in another thread

**Comment by nbenty** [comment]
Are you syncing the threads?
`mpFrameFence` is signaled on `present()`, you need to make sure that `present` is called *after* you submit the second context.

**Comment by bryan05** [comment]
when the second render contex runs every frame, it's fine, no error

**Comment by nbenty** [comment]
Are you pre-recording commands in a different frame then the frame you call `flush()` on?

**Comment by bryan05** [comment]
the code is like this```
    void Device::present()
    {
		if ((engine.frame % 3 == 0))
		{
		//	mpSecondRenderContext->resourceBarrier(mpSecondRenderContext->getGraphicsState()->getFbo()->getColorTexture(0).get(), Falcor::FResource::State::Present);

			mpSecondRenderContext->flush();
		}
		
		mpRenderContext->resourceBarrier(mpSwapChainFbos[mCurrentBackBufferIndex]->getColorTexture(0).get(), FResource::State::Present);
        mpRenderContext->flush();

        apiPresent();
        mpFrameFence->gpuSignal(mpRenderContext->getLowLevelData()->getCommandQueue());

		if ( (engine.frame % 3 == 0))
		mpFrameFence->gpuSignal(mpSecondRenderContext->getLowLevelData()->getCommandQueue());


        executeDeferredReleases();
        mFrameID++;
    }
```

**Comment by bryan05** [comment]
> Are you pre-recording commands in a different frame then the frame you call flush() on?
I think they are in the same frame

**Comment by nbenty** [comment]
```

**Comment by bryan05** [comment]
after removing that , I got the same error.

**Comment by nbenty** [comment]
I'll need to write a test for it and debug it. Unfortunately I won't be able to debug it until after SIGGRAPH.

A possible workaround is to submit the second context every frame, but only record commands every 3 frames (submit an empty list the other 2 frames).

**Comment by bryan05** [comment]
thanks i'll try that

**Comment by bryan05** [comment]
> A possible workaround is to submit the second context every frame, but only record commands every 3 frames (submit an empty list the other 2 frames).

it worked
