### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#106]
1. for every draw call, the following function is run. if the buffer changed(prepareResource), why do you set mRootSets[s].pSet null, this will cause a new descriptor set created. 
```
    bool ParameterBlock::prepareForDraw(CopyContext* pContext)
    {
        // Prepare the resources
        for (size_t s = 0; s < mAssignedResources.size(); s++)
        {
            const auto& set = mAssignedResources[s];
            for (const auto& range : set)
            {
                for (const auto& desc : range)
                {
                    if (prepareResource(pContext, desc.pResource.get(), desc.type))
                    {
                       mRootSets[s].pSet = nullptr; 
                    }
                }
            }
        }
```
2. in every draw call, if the constant buffer is changed(dirty), you set constant buffer view to nullptr, this will also cause mpCbv to created. I don't think constant buffer view should generated in every frame
```
   bool ConstantBuffer::uploadToGPU(size_t offset, size_t size)
    {
        if (mDirty) mpCbv = nullptr; 
        return VariablesBuffer::uploadToGPU(offset, size);
    }
```

**Comment by nbenty** [comment]
1. If the buffer changed, it's GPU address changed and we need to change the descriptor set. Since the current descriptor set might still be in used by a previous frame, we have to reallocate and set a new set.
2. Same thing. The CBV contains the GPU virtual address. Constant buffers are created on the upload heap, if they changed it means we had to use a new chunk and the GPU address changed.

**Comment by bryan05** [comment]
If we don't change the size of the buffer and only change the content of the buffer, do we still need to reallocate a new descriptor set or CBV?

**Comment by nbenty** [comment]
Yes, unless you know for sure that the current allocation is not being used by any draw calls which are in-flight, which is rare.
