### ISSUE TITLE
use latest slang library up to end of day 7/31

### ISSUE THREAD

**Issue by kenchen3000** [NVIDIAGameWorks/Falcor#107]
Hi,
Slang fixes a couple of shader compile problems which was causing errors for SceneEditor and ComputeShader samples. Can these fixed be pushed into latest dependent slang lib for Falcor? The latest fix for slang is:
https://github.com/shader-slang/slang/commit/5ea746a571ced32a8975eb3a238c562b3d487149

Thank you.

**Comment by tfoleyNV** [comment]
Please note that it is possible, but not officially supported, for Falcor users to manually update the `dependencies.xml` file at the root of the Falcor source tree to specify a different version to use for the Slang library (corresponding to the release versions on the Slang GitHub project).

**Comment by kenchen3000** [comment]
thanks, we are modifying the version in xml file like you said.
