### ISSUE TITLE
crash with same GraphicsProgram, but different GraphicsVars

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#108]
I have 4 rendercontex, every one has different GraphicsVars, different GraphicsState. but they all use the same GraphicsProgram, which is set in the different GraphicsState.
the program looks like:
```
	pProgram = Falcor::GraphicsProgram::create(d);
		for (int i = 0; i < 4; i++)
		{
		
			pVars[i] = Falcor::GraphicsVars::create(pProgram->getActiveVersion()->getReflector());
		}
```

crash when run setBlob:
```
	Falcor::ConstantBuffer::SharedPtr const_buf = pVars[state_index]->getConstantBuffer(name);
	const_buf->setBlob(buffer->data, 0, buffer->size * sizeof(int));

```

![ft99n1 2h mre gpz47g](https://user-images.githubusercontent.com/14899259/43612388-0ecfdba0-9661-11e8-94a0-ac0115ce4001.png)

**Comment by nbenty** [comment]
What's the value of `state_index? `pVars[state_index]`?
I can't reproduce it, I suspect something is wrong with the `pVars` array

**Comment by bryan05** [comment]
State_index is from 0 to 3, I have 4 GraphicsVars.

**Comment by bryan05** [comment]
I forget to mention I run setBlob of constant buffer in different threads, there are four threads. We assign every thread a render context. If we run this in the same thread there is no error.

**Comment by nbenty** [comment]
That might be the problem. `setBlob` is not thread safe. In fact, the `ConstantBuffer` class is not thread safe. You should have a different CB per thread or sync it yourself

**Comment by bryan05** [comment]
![b i4u08ha4c89m 3m5 ag4w](https://user-images.githubusercontent.com/14899259/44438513-52dffb00-a574-11e8-82e0-f43f162fd137.png)
there is another crash, when multi thread recording.

**Comment by nbenty** [comment]
All those objects are not thread safe. For each thread you'll need a different GraphicsVars and GraphicsState objects.

Alternatively, you'll have to dig into the code and add critical sections.

We will add proper multi-thread support once the RenderGraph system is ready, but that will take a while.

**Comment by bryan05** [comment]
> Alternatively, you'll have to dig into the code and add critical sections.
thanks, it worked. 
I encounter other crashes, these crashes doesn't happen in the multi thread recording, but after that.
![ww583 o8tw 8_yno hpq](https://user-images.githubusercontent.com/14899259/44612111-9461e780-a7ba-11e8-8be4-df39be9f766a.png)

**Comment by bryan05** [comment]
![8mvarbq 7 e br17924 bp](https://user-images.githubusercontent.com/14899259/44612249-98423980-a7bb-11e8-8ec2-695cdbcf3571.png)
`	D3D12RenderRenderer::stopThread(0);

	for (int i =0; i <4; i++)
	{
		D3D12Ext::getDevice()->getRenderContext(i)->flush(true);
	}
`
after the multi threading I flush every render contex.

**Comment by bryan05** [comment]
d3d error
 is 

> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x00000188DD250B20:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x80: D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) of resource (0x00000188891D37D0:'Unnamed ID3D12Resource Object') (subresource: 0) specified by transition barrier does not match with the state (0x4: D3D12_RESOURCE_STATE_RENDER_TARGET) specified in the previous call to ResourceBarrier [ RESOURCE_MANIPULATION ERROR #527: RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH]

**Comment by nbenty** [comment]
We've just hit a brick wall (but should be a simple fix).

The problem is that the resources track a *global* state, where global means the-last-time-we-called-resourceBarrier-on-whatever-context.

We will need to store a resource-state *per-context*. I need to think about how to do it correctly/efficiently in Falcor.

For now, you can store a `std::unordered_map<Resource, Resource::State>` in `RenderContext` and use it for state transitions.

**Comment by bryan05** [comment]
this crash happens after multithreading,

**Comment by bryan05** [comment]
find the solution, after I added a critical section to descriptor set creation, the crash is gone.
```
				EnterCriticalSection(&ghMutex);
                DescriptorSet::Layout layout;
                const auto& set = mpReflector->getDescriptorSetLayouts()[i];
                mRootSets[i].pSet = DescriptorSet::create(gpDevice->getGpuDescriptorPool(), set);
				LeaveCriticalSection(&ghMutex);
```

**Comment by bryan05** [comment]
now the multithread command lists recording run smoothly, no crash, thanks

**Comment by nbenty** [comment]
Cool.

Any chance you can submit a pull-request with your fixes? No need to clean it up or anything, I'd like to see all the changes you made to get multithreading to work.

**Comment by bryan05** [comment]
Just did it.
