### ISSUE TITLE
Have trouble building with spaces in user folder path

### ISSUE THREAD

**Issue by hustanhuang** [NVIDIAGameWorks/Falcor#11]
Unfortunately my Windows user folder happened to be "C:\Users\Andrew Huang", with a SPACE in it.

So when I compiled the solution in VS2017, it failed.

Here is the log.
```
1>------ Build started: Project: Falcor, Configuration: DebugD3D12 x64 ------
1>Fetching python@2.7.6-windows-x86.exe from s3 ...
1>Connecting to S3 ...
1>Downloading ...
1>Error connecting to S3!
1>System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "2" argument(s): "Access to the path 'C:\Users\Andrew' is denied." ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Andrew' is denied.
1>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
1>   at System.IO.FileStream..ctor(String path, FileMode mode)
1>   --- End of inner exception stack trace ---
1>   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
1>   at System.Management.Automation.DotNetAdapter.InvokeResolvedConstructor(MethodInformation bestMethod, Object[] newArguments, Object[] arguments)
1>   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
1>   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)
```

Oh, and I've installed the python module for VS2017. So it puzzles me why I have to download a python 2.7 again.

**Comment by hustanhuang** [comment]
Sorry, I didn't read the prerequisites thoroughly.

Do I have to use VS2015 to compile it?

**Comment by nbenty** [comment]
Our test system uses VS2015. AFAIK some users were able to use VS2017 without any issues.

This looks like an issue with the package manager we are using.
Can you check the value of `PM_PACKAGES_ROOT` environment variable?

**Comment by halldorfannar** [comment]
Sorry to hear about this issue. I think I know what is going wrong and should be able to post a fix after the weekend.

**Comment by hustanhuang** [comment]
@nbenty I think it's "C:\packman-repo"

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Andrew Huang>set
 ...
PM_PACKAGES_ROOT=C:\packman-repo
 ...
```

**Comment by halldorfannar** [comment]
@hustanhuang Please pull latest and try again. Should be working for you now.  Thanks for reporting the issue.  If you still get errors please reopen this issue.

**Comment by bailehang** [comment]
It`s the latest, Thank you for help.
-------------------------------------------------------------------------------
Connecting to S3 ...
1>Downloading ...
1>Error connecting to S3!
1>System.Management.Automation.MethodInvocationException: 使用“3”个参数调用“Read”时发生异常:“操作已超时。” ---> System.Net.WebException: 操作已超时。
1>   在 System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
1>   在 CallSite.Target(Closure , CallSite , Object , Object , Int32 , Object )

**Comment by nbenty** [comment]
@halldorfannar Can you help?
