### ISSUE TITLE
Vulkan raytracing support?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Falcor#111]
Seems nsight graphics already supports debugging apps using that extension..
In fact new Nsight YouTube video shows rendering bistro scene so maybe using Falcor..
Now all that’s missing is a new driver supporting it and some Falcor support..
I understand maybe a bit too early and have to wait until Turing hardware ships albeit I have a Volta Gpu..
Thanks..

**Comment by nbenty** [comment]
When Vulkan will officially support raytracing (including drivers and runtime), so will Falcor.
Can't say when that will happen.

**Comment by oscarbg** [comment]
Vulkan Rt drivers are here!

**Comment by oscarbg** [comment]
@nbenty no pressure but some ETA? now that ecosystem is ready (Vulkan SDK 1.1.85 supports it too).. some version number hint of when to expect it, like 3.2?
Thanks.,

**Comment by nbenty** [comment]
No ETA, it's low on our priority list

**Comment by horusli** [comment]
> No ETA, it's low on our priority list

how about now? do we have a ETA for this?
