### ISSUE TITLE
San Miguel fscene file

### ISSUE THREAD

**Issue by Woking-34** [NVIDIAGameWorks/Falcor#112]
Hi,

Can I access/download somehow the fscene file for the San Miguel scene? Thanks.

**Comment by nbenty** [comment]
I don't think we have a canonical scene file for Sun Miguel. You can use the scene editor to create something.

@kyaoNV can you attach a scene file to this issue?

**Comment by kyaoNV** [comment]
Here is a sample [fscene](https://github.com/NVIDIAGameWorks/Falcor/files/2295657/SanMiguel.txt). GitHub will only let me upload it as a `.txt` file but it should still work.

This scene file will work with the version of San Miguel downloaded from [here](http://casual-effects.com/data/). You may need to edit the scene file if you have a different version.

Also, note that the model file path in the scene file assumes it is in the same directory as the model file. You may need to change this as well.

**Comment by Woking-34** [comment]
Thanks!

**Comment by DouYishun** [comment]
@kyaoNV Hi,
Can I access/download somehow the pyscene files for the ZeroDay_v1 and Attic?
Thanks.
