### ISSUE TITLE
setSrv() crash when dxr pass run after rasterization pass 

### ISSUE THREAD

**Issue by boksajak** [NVIDIAGameWorks/Falcor#114]
Hi

I am experiencing a crash when running depth pre-pass (from forward rendering sample) followed by raytracing pass (from hello DXR). In debug mode the application works as expected but I get following warnings:

Can't find resource at set index 0, range index 17, array index 0. Ignoring setSrv() call
Can't find resource at set index 0, range index 16, array index 0. Ignoring setSrv() call
Can't find resource at set index 0, range index 15, array index 0. Ignoring setSrv() call

It seems like during the renderScene() call with ray tracing program, the falcor is still trying to bind SRVs setup by previous rendering pass - problem is that warnings are issued already during the depth prepass and only when following raytracing pass is enabled which confuses me. Without the RT pass, it works as expected.

An advice will be appreciated, maybe I'm just missing some state setup calls to reset SRVs?

Thank you

**Comment by nbenty** [comment]
How do you bind the `GraphicsVars` before the depth-pass and the RT pass?

**Comment by boksajak** [comment]
Hi, it's the following for depth pass:

```
        mDepthPass.pVars = GraphicsVars::create(mDepthPass.pProgram->getReflector());
...
	mpGraphicsState->setFbo(mpDepthPassFbo);
	mpGraphicsState->setProgram(mDepthPass.pProgram);

	pContext->setGraphicsVars(mDepthPass.pVars);
```
for RT pass I tried this with no success:
```
        mpRtVars = RtProgramVars::create(mpRaytraceProgram, mpScene);
...
	pContext->setGraphicsVars(mpRtVars->getGlobalVars().get());
```

I can also share the whole source with you if desired, via email (listed on my github profile page). Thanks

**Comment by nbenty** [comment]
You don't need to call setGraphicsVars() when you raytrace, it's only used for rasterization.
Do you use a `SceneRenderer` or `RtSceneRenderer`?

**Comment by nbenty** [comment]
Can you try and create a regular `SceneRenderer` for the depth-pass?

**Comment by boksajak** [comment]
I will try that and get back with results on Monday. (I am now out of office for the rest of the week)

**Comment by boksajak** [comment]
Using regular SceneRenderer worked, thank you
