### ISSUE TITLE
RenderGraph

### ISSUE THREAD

**Issue by nbenty** [NVIDIAGameWorks/Falcor#116]
Please don't remove items from the list. Use strikethough instead (~~)

- ~~Make the menu bar color different~~
- ~~RenderGraphEditor should load faster (no need to load the scene, skybox, whatever)~~
- ~~Support multiple graphs in viewer and editor~~
- ~~Resizing the editor window should resize the GUI windows~~
- ~~Don't lock the editor windows~~
- ~~The color of the selected passes is very similar to the colors of the inactive passes. Need to make it more pronounced~~
- ~~Editor - When the render-passes window is hidden behind another window, clicking inside a `RenderPass` box (which is hidden behind) brings the render-passes window to the front~~
- ~~Add debug windows in the viewer that allow you to view different outputs. These windows should have a `saveToFile` option)~~
- ~~Add the option to render a specific pass' UI~~
- ~~Check that the graph is valid before saving the file (display an "are you sure" warning message)~~

**Comment by pclarberg** [comment]
Requests:

- `RenderGraph::addRenderPass` returns unique index that can be used to specify execution order.
- `RenderGraph::getPassIndex(name)` function that maps name to index.
- `onMouseEvent` and `onKeyEvent` on `RenderGraph` that calls those functions on all active passes in execution order.
- `Field::setDimensions` default values.
- `RenderGraphUI::SharedPtr` and `RenderGraphUI::create(graph)`, and that it stored a shared ptr to `RenderGraph` internally.
- `RenderGraph::renderUI` doesn't draw the passes UI's, or there is a way for me to make my own UI incl the profiling stuff that renderUI does now.
- `bool RenderPass::active()` function that is called upon first use, or when switching to a graph.
- `void RenderPass::deactive()` function that is called when graph is "deactivated".
- `activate/deactivate` functions on `RenderGraph` that calls the above.
