### ISSUE TITLE
crash after closing the application

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#119]
I encounter a weird crash, when I close the window. 

![m en hfh3 7s0xg y p o](https://user-images.githubusercontent.com/14899259/44756979-9fca5100-aae1-11e8-8527-63d0916efa95.png)

**Comment by bryan05** [comment]
```
class RenderContext : public ComputeContext, public inherit_shared_from_this<ComputeContext, RenderContext>
{
............................
        static CommandSignatureHandle spDrawCommandSig;
        static CommandSignatureHandle spDrawIndexCommandSig;
```
 spDrawIndexCommandSig is static, so when I create two renderContext instances. the following function run twice.

```
    void RenderContext::initDrawCommandSignatures()
    {
          .........
        gpDevice->getApiHandle()->CreateCommandSignature(&sigDesc, nullptr, IID_PPV_ARGS(&spDrawIndexCommandSig));
    }
```

**Comment by nbenty** [comment]
Nice catch. I'll add an `if` statement to make sure we don't initialize it twice.
Thanks!

**Comment by bryan05** [comment]
sorry I just missed
```
    RenderContext::RenderContext()
    {
        if (spDrawCommandSig == nullptr)
        {
            initDrawCommandSignatures();
        }
    }
```

**Comment by bryan05** [comment]
after I call detach function of spDrawIndexCommandSig specifically by myself, not by  application. the crash disappear. The only difference is that I put falcor source files into a dll. Is this a problem?

**Comment by nbenty** [comment]
Do you call `UnloadDLL` yourself or let the app do it on exit?

**Comment by bryan05** [comment]
app do it on exit.

**Comment by nbenty** [comment]
You should call probably call `UnloadDLL` yourself to control the order in which static objects get destroyed. Not sure if that will help.

We need to make sure that we destroy all the static objects ourselves on not rely on the runtime to do it for us

**Comment by nbenty** [comment]
That suggests that someone is deleting the device before the application automatically unloads the DLL. 
Did you try unloading the DLL yourself?

**Comment by bryan05** [comment]
after the compilation of falcor we have a dll file and a lib file. We link the lib file into our main program(exe), so we don't need to unload dll. we can create and delete the object directly.

**Comment by nbenty** [comment]
In that case we need to move `Sample::~Sample()` into a public function `Sample::shutdown()`, then the app can call it when it's ready to quit.

It won't work now - we still rely on the runtime to destroy static objects, to calling `shutdown()` will still result in a crash.

Dynamically loading/unloading is the best I can offer at the moment. Hopefully it solves the problem.
