### ISSUE TITLE
Feature request: option to display pixel values under mouse

### ISSUE THREAD

**Issue by mmp** [NVIDIAGameWorks/Falcor#122]
It would be nice to have an option to be able to see the actual numeric values of a pixel under the mouse (possibly just with the VisualizerPass).

**Comment by nbenty** [comment]
Do you care about perf when the values are displayed?
It's straightforward if we do sync reads from the texture

**Comment by mmp** [comment]
In this case, perf seems unimportant to me (as long as the perf cost is only when "display the pixel values" is happening.)
