### ISSUE TITLE
Verify that SM 6.x compiles and runs correctly

### ISSUE THREAD

**Issue by nbenty** [NVIDIAGameWorks/Falcor#129]
The user can ask for SM6.x by calling `Program::Desc::setShaderModel()`.
Looking at the code, we already request Slang to compile them to DXIL.

We need to verify that it actually works and we can create a PSO from DXIL shaders. We also need to make sure that it works on Win10-RS2 (I think it was an experimental feature, but I'm not sure)

**Comment by kyaoNV** [comment]
Merged PR #80 into `dev-3.1.0`
