### ISSUE TITLE
Missing Linux functions

### ISSUE THREAD

**Issue by nbentyNV** [NVIDIAGameWorks/Falcor#137]
isProcessRunning()
terminateProcess()
setActiveWindowIcon()
getDisplayDpi()
getDisplayScaleFactor()

**Comment by nbenty** [comment]
fileDialogCommon() doesn't use the `filters` argument

**Comment by Ishaan28malik** [comment]
@nbenty can u assign this to me ?

**Comment by nbenty** [comment]
@Ishaan28malik Thanks for offering to help.
Unfortunately I can't assign it to you because you are not a part of the organization. If you have a fix and would like to submit a pull-request, I will be happy to merge your changes in.

**Comment by Ishaan28malik** [comment]
ok @nbenty
