### ISSUE TITLE
Does Falcor require D3D feature level greater than 12_0?

### ISSUE THREAD

**Issue by DQLin** [NVIDIAGameWorks/Falcor#146]
My graphics card is GTX 960M, which supports D3D feature level up to 11_0. It runs Microsoft's D3D12 samples (DirectX-Graphics-Samples) with no problem. However every Falcor sample crashes when I compile in DebugD3D12 or ReleaseD3D12 mode and it seems like creating resources for textures caused the problem. The log reads: (this is the result of running AmbientOcclusion.exe, but all other executables gave the same error)

(Logger::Level::Warning)	Converting 24-bit texture to 32-bit
(Logger::Level::Warning)	Converting 24-bit texture to 32-bit
(Logger::Level::Warning)	Converting 24-bit texture to 32-bit
(Logger::Level::Error)	mpList->Close().
Error! Unspecified error

(Logger::Level::Error)	mpList->Reset(mpAllocator, nullptr).
Error! Unspecified error

(Logger::Level::Warning)	Converting 24-bit texture to 32-bit
(Logger::Level::Error)	gpDevice->getApiHandle()->CreateCommittedResource(&kDefaultHeapProps, D3D12_HEAP_FLAG_NONE, &desc, D3D12_RESOURCE_STATE_COMMON, pClearVal, IID_PPV_ARGS(&mApiHandle)).
Error! The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

GetDeviceRemovedReason turned out to be DXGI_ERROR_INVALID_CALL. I wonder if there are some API calls with some parameters that are not supported in lower feature levels.

**Comment by Alekssasho** [comment]
I had similar issue, and it was due to Falcor trying to setup sample position but my graphics card didn't support it. I managed to fix it with commenting out a call to D3D12SetSamplePositions() in D3D12RenderContext.cpp - https://github.com/NVIDIAGameWorks/Falcor/blob/master/Framework/Source/API/D3D12/D3D12RenderContext.cpp#L293

**Comment by AireSpringfield** [comment]
> I had similar issue, and it was due to Falcor trying to setup sample position but my graphics card didn't support it. I managed to fix it with commenting out a call to D3D12SetSamplePositions() in D3D12RenderContext.cpp - https://github.com/NVIDIAGameWorks/Falcor/blob/master/Framework/Source/API/D3D12/D3D12RenderContext.cpp#L293

Works for me! Thx!

**Comment by BrennenTaylor** [comment]
I also ran into this problem. At first, I commented out the same line of code y'all are discussing.

However, I've come to find that I believe the following is a more "Falcor-correct" approach.
https://gist.github.com/BrennenTaylor/e38e98669f98ddf9333f0614d32c2b0a

The render context allows you to specify the binding behavior of the pipeline, and thus through that flag system, you can disable binding sample positions. By default, the render context is created with all flags set: https://github.com/NVIDIAGameWorks/Falcor/blob/master/Framework/Source/API/RenderContext.h#L227

**Comment by nbenty** [comment]
That's a bug, Falcor should take care of that implicitly.
We will fix it.

**Comment by kyaoNV** [comment]
3.1 now checks sample position support implicitly and won't call the function if not supported. Also noticed that we had a hardcoded feature level that overwrote the user setting/define. That has been fixed as well.
