### ISSUE TITLE
Samples are not running out of the box on older cards (GTX 760)

### ISSUE THREAD

**Issue by Alekssasho** [NVIDIAGameWorks/Falcor#151]
By default Falcor 3.1 tries to use d3d12 feature level 12.0 which is not supported on some older cards like GTX 760 which leads to samples not starting. In previous version D3D12 device was created with feature level 11.0, and was later changed by this commit https://github.com/NVIDIAGameWorks/Falcor/commit/aa2776f8bcaeffa3962e520ed1f68077fd01655f.

Maybe it is possible to try creating multiple D3D12 devices with different feature levels until one is found, instead of just trying only with 1 and failing.

**Comment by nbenty** [comment]
We should the way `Device::Desc` handle feature-level. 
Set `majorVersion` to -1 by default, which means create the highest feature-level possible.

@kyaoNV We should fix it and create a 3.1.1 version

**Comment by nbenty** [comment]
@kyaoNV Was this fixed in Falcor 3.2?
