### ISSUE TITLE
rtx2070 can't run

### ISSUE THREAD

**Issue by yaoyutian** [NVIDIAGameWorks/Falcor#152]
![image](https://user-images.githubusercontent.com/10574966/47516479-2324da80-d8b8-11e8-8803-0b726ea0a924.png)
sdk 17763
rtx2070 
driver 416.34
OS 17763.104
output:
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\HelloDXR.exe'. Symbols loaded.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\FalcorSharedObjects.dll'. Symbols loaded.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\python37.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Symbols loaded.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Unloaded 'C:\Windows\System32\msvcrt.dll'
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\d3d12.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\openvr_api.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Unloaded 'C:\Windows\System32\sechost.dll'
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\assimp-vc140-mt.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\FreeImage.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Unloaded 'C:\Windows\System32\ucrtbased.dll'
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17763.104_none_05b337a607211969\comctl32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\avcodec-58.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\avutil-56.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\avformat-58.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\glfw3.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\slang.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\vcomp120.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\swresample-3.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\swscale-5.dll'. Module was built without symbols.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msvcp110_win.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ncrypt.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ntasn1.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\XInput1_4.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\d2d1.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\rmclient.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\d3d12SDKLayers.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\DXGIDebug.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Unloaded 'F:\CPProject\Falcor\Bin\x64\Debug\DXGIDebug.dll'
'HelloDXR.exe' (Win32): Unloaded 'F:\CPProject\Falcor\Bin\x64\Debug\d3d12SDKLayers.dll'
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\DXGIDebug.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f4187dc256a67a6b\nvldumdx.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f4187dc256a67a6b\nvwgf2umx.dll'. Cannot find or open the PDB file.
The thread 0x306c has exited with code 0 (0x0).
'HelloDXR.exe' (Win32): Loaded 'F:\CPProject\Falcor\Bin\x64\Debug\d3d12SDKLayers.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\dxilconv.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\D3DSCache.dll'. Cannot find or open the PDB file.
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFD9ED25299 in HelloDXR.exe: Microsoft C++ exception: _com_error at memory location 0x000000D703CF7C90.
'HelloDXR.exe' (Win32): Unloaded 'C:\Windows\System32\dxilconv.dll'
'HelloDXR.exe' (Win32): Loaded 'C:\Windows\System32\dxilconv.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFD9CC1EB7E (dxgi.dll) in HelloDXR.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by nbenty** [comment]
Did you run it in debug?
If you did, can you post the debug message from the output window?

**Comment by yaoyutian** [comment]
output updated

**Comment by yaoyutian** [comment]
I git clone a new master repo ,it seems works fine!
maybe when I first try falcor 3.0, update_dependencies.bat download some resources very slowly and did't exit normally。or Maybe I did't use github/git correctly,i just use "git clone"  to clone this repo,and update by"git reset --hard origin/master ;git pull"(@﹏@)~.
