### ISSUE TITLE
Incorrect Frame Size at 4k

### ISSUE THREAD

**Issue by NTimmons** [NVIDIAGameWorks/Falcor#153]
I am dumping image captures from scenes for comparison at different resolutions. 

Setting the window size from Window.h to 1920x1080 lets me capture frames which output as 1080p as expected.

Setting this to 3840x2160 gives me an image with output dimensions of 3840x2130

![aa_fxaa](https://user-images.githubusercontent.com/16775925/47573447-45107280-d935-11e8-9c09-0a9f1c56287c.png)
![aa_4k_ss](https://user-images.githubusercontent.com/16775925/47573448-45107280-d935-11e8-9a12-b6b596f55758.png)

**Comment by NTimmons** [comment]
This is the cause:

    void Window::checkWindowSize()
    {
        // Actual window size may be clamped to slightly lower than monitor resolution
        int32_t actualWidth, actualHeight;
        glfwGetWindowSize(mpGLFWWindow, &actualWidth, &actualHeight);

        mWidth = uint32_t(actualWidth);
        mHeight = uint32_t(actualHeight);
        mMouseScale.x = 1.0f / (float)mWidth;
        mMouseScale.y = 1.0f / (float)mHeight;
    }

mWidth and mHeight begin correct but glfwGetWindowSize returns the clipped height.

My current guess is that:
         GLFWwindow* pGLFWWindow = glfwCreateWindow(desc.width, desc.height, desc.title.c_str(), mon, nullptr);

Can't create a window larger than the desktop resolution?

Investigating further.

**Comment by nbenty** [comment]
That's not a GLFW issue, it's a Windows issue. `CreateWindows` clamps the size of the requested window the desktop size.
If you want 4K:
* If you have a 4K monitor, run the samples in fullscreen mode
* If you don't have a 4K monitor you can create a 4K render-target and blit it

**Comment by NTimmons** [comment]
Fair enough.
If I push a commit with a warning that pops up when this happens would that be accepted? Just in-case any one hits or trips on this behaviour, as its odd. Windows supports windows of (basically) any size.

**Comment by nbenty** [comment]
Sure.
I just found this - https://stackoverflow.com/questions/445893/create-window-larger-than-desktop-display-resolution

Apparently it's an OS restriction but there's a way to override it. I'm keeping this issue open for now
