### ISSUE TITLE
Shadow Flickering in Vulkan Build Of Forward Renderer Demo

### ISSUE THREAD

**Issue by NTimmons** [NVIDIAGameWorks/Falcor#154]
There is some intense shadow flickering in the Vulkan Build of the Forward Renderer.
Stops when shadows are disabled

**Comment by nbenty** [comment]
I can't reproduce it (Windows 10 RS5, Titan-V).
What's your configuration? Which version of Falcor?

**Comment by NTimmons** [comment]
I cloned the repo yesterday (commit 5a12f298c15b82297447906afafdcf5a2f58f99e).
I am on an NVidia 1080, Windows 10 Pro, Version	10.0.17134 Build 17134

**Comment by nbenty** [comment]
Still can't reproduce it.
What driver version are you using?

**Comment by johnfettig** [comment]
This is happening on my machine also with the same commit. Ubuntu 16.04, GeForce GTX 1080 Ti with 390.87 drivers.

**Comment by nbenty** [comment]
I tried 5 different machines - Linux/Windows with different GPUs. Still can't reproduce it.
It's probably a timing/resource-barrier issue. I'll keep looking

**Comment by NTimmons** [comment]
Sorry, I was away for a few days.

I am on an older driver, 385.54
Let me know if you want me to do a capture if it will help diagnose the issue

**Comment by NTimmons** [comment]
Unfortunately I can't. This machine is being used for testing TensorFlow things that required that version for the GPU support at when we started testing.

I'll try updating if this is still an issue when that finishes.

**Comment by TechnikEmpire** [comment]
When running the shadows example with vulkan on 1060 I'm getting 4 fps. Is this related?

**Comment by fl0at88** [comment]
me too

**Comment by fl0at88** [comment]
> When running the shadows example with vulkan on 1060 I'm getting 4 fps. Is this related or should I open a new ticket?

me too
