### ISSUE TITLE
"Package '7za' at version '16.02.2' is missing from local storage" in Windows 10 RS5

### ISSUE THREAD

**Issue by GreyWolfHK** [NVIDIAGameWorks/Falcor#156]
Hi,

I downloaded the tutorial code from the siggraph 2018 course( here's the website: http://intro-to-dxr.cwyman.org ), and when I try to build this project, I run into this problem. It showed error MSB3073,
and output in VS 2017 showed the following message:
"Package '7za' at version '16.02.2' is missing from local storage" .
I ran this project in Windows 10 v1809( OS version 17763.104 ).
I think the error is coming from Falcor 'cause I downloaded the newest release version of Falcor, and the same error occurred when I tried to run update_dependencies.bat.

Do you know how to fix this problem? Many thanks.

**Comment by halldorfannar** [comment]
Please run `packman.bat --version` from within the packman folder in the repository and post the results here.  Thanks!

**Comment by GreyWolfHK** [comment]
Thanks for the replies, turns out it's a network-connection problem. I had a bad network, and now it is solved. 

Sorry if it wasted your time, and I wish you all the best! :)
