### ISSUE TITLE
Feature Request: Enable loading GLTF Assets

### ISSUE THREAD

**Issue by Alekssasho** [NVIDIAGameWorks/Falcor#157]
Assimp has support for GLTF models. However the supported format strings for models(Models.cpp: kSupportedFileFormatsStr) does not include gltf.
I have tried loading some gltf assets from ScetchFab and it loaded them properly. 

Is there some reason gltf is not included in the supported models ?
And if not can you add it so no framework modification are needed to be able to load them ?

**Comment by nbenty** [comment]
Legacy reason. Previous versions of ASSIMP didn't support glTF correctly, so we left it out.
I agree we should support it.

@kyaoNV Any chance we can fit it into 3.1.1?

**Comment by kyaoNV** [comment]
Just a bit late for 3.1.1, but I'll get it in for 3.1.2

**Comment by kyaoNV** [comment]
Fixed as part of 3.2 release
