### ISSUE TITLE
RX Vega support?

### ISSUE THREAD

**Issue by capitalknew** [NVIDIAGameWorks/Falcor#16]
Hello. Falcor has the support of AMD RX Vega graphics card?

**Comment by nbenty** [comment]
It should, but we never tested it on RX Vega.

**Comment by capitalknew** [comment]
RX Vega device not enumerating. AMD support only 51 version of Vulkan API.

**Comment by nbenty** [comment]
Strange, we are using SDK version 1.0.51.0, so it should work.
We ordered some Vega cards - we'll debug this issue when we get them.

**Comment by capitalknew** [comment]
This is my fault, just my driver not run Vulkan. I fixed it.

**Comment by nbenty** [comment]
NP, thanks for the update.

**Comment by capitalknew** [comment]
I want ask question. Falcor will support of Linux?

**Comment by nbenty** [comment]
Yes, we're actively working on it.
