### ISSUE TITLE
wrong Scale values

### ISSUE THREAD

**Issue by GregSlazinski** [NVIDIAGameWorks/Falcor#166]
https://github.com/NVIDIAGameWorks/Falcor/blob/master/Framework/Source/Utils/Platform/Windows/Windows.cpp#L279

```
 case SCALE_175_PERCENT: return 1.70f;
 case SCALE_500_PERCENT: return 4.60f;
```

**Comment by nbenty** [comment]
We should convert that `switch(factor)` to `float(factor)*0.01f;
