### ISSUE TITLE
Setting GraphicsState vao to nullptr crashes if vao was previously set

### ISSUE THREAD

**Issue by Qbz23** [NVIDIAGameWorks/Falcor#17]
GraphicsState::setVao() 
crashes with a read access violation if you try to set it to nullptr after it was previously set to some value. 
On line 177 of GraphicsState.cpp, code attempts to GetVertexLayout() on pVao, which is nullptr. 

This issue will not happen if set to nullptr initially b/c it wont pass the mpVao != pVao check on line 168. To repro, set gfx state vao to a vao, then set it to nullptr.

**Comment by nbenty** [comment]
Thanks!

@kyaoNV Please fix it
