### ISSUE TITLE
DXR Acceleration Structure is not showing in debug tools

### ISSUE THREAD

**Issue by Alekssasho** [NVIDIAGameWorks/Falcor#172]
Running HelloDXR Sample with PIX or NVIDIA Nsight Graphics tools does not show the acceleration structure properly. PIX says it is not bound, and Nsight says that there is not Descriptor Heap bound for that argument. Running those tools on https://github.com/NVIDIAGameWorks/DxrTutorials works correctly, and the structure is shown in the tools.
PIX version is 1812.14 and Nsight version is 2018.7.0.0 with Driver version GeForce 417.22 with RTX 2070

Here is a screenshot of Nsight:
![image](https://user-images.githubusercontent.com/1225431/50546190-43607500-0c2c-11e9-8896-377e04eb270c.png)

Here is one from PIX:
![image](https://user-images.githubusercontent.com/1225431/50546228-d7cad780-0c2c-11e9-8860-59cca2cc5f41.png)

**Comment by nbenty** [comment]
I think it's a PIX bug.
All the resources that can't be displayed are part of the global root signature (marked with `shared` in our shaders). Perhaps PIX doesn't support it, I'll check with Microsoft.

If you need to debug it I suggest to manually bind the TLAS into the RGS.

**Comment by Alekssasho** [comment]
Binding TLAS into RGS made it work for both Nsight and PIX so I will debug it that way if needed.
If it is a bug in PIX, is the same bug in Nsight, or it is not showing there for another reason ?
