### ISSUE TITLE
Compilation fails on Arch Linux

### ISSUE THREAD

**Issue by MrKickkiller** [NVIDIAGameWorks/Falcor#177]
Hi,

I'm trying to compile Falcor on my Arch Linux development machine, but I am running into various compile errors.

Assuming that the code is compileable on other platforms, I would like to know what is different with my machine that it does not compile. To me the errors appear to be errors in the source, but I find this hard to believe.

Output of `make`: https://pastebin.com/6WNw0J52

**Comment by angelskieglazki** [comment]
Output is missing. Have you compilation error still?

**Comment by angelskieglazki** [comment]
@MrKickkiller Output is missing. Have you compilation error still?
