### ISSUE TITLE
What's the purpose of this static vector in the destructor of RenderTargetView

### ISSUE THREAD

**Issue by crujose** [NVIDIAGameWorks/Falcor#179]
https://github.com/NVIDIAGameWorks/Falcor/blob/2d424d3a498d545f2f8b1c4921176e35b9ced4dd/Framework/Source/API/Vulkan/VKResourceViews.cpp#L189

Wouldn't this just grow indefinitely until the application closes?

**Comment by nbenty** [comment]
It's probably debug code but looking at what it does it might be important (pushing objects to the vector keeps the API view alive).

I'll have to debug and test it before removing it.

Nice catch! Thanks
