### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gamagan** [NVIDIAGameWorks/Falcor#18]
Hi folks,

Falcor is a really awesome piece of software. I just came across it, and I find it really impressive. Thank you so much for all the work you're doing. 

So, Github projects can have Wikis. I'm wondering if there are plans to write some introductory documentation for using the framework. I know there is a samples folder with some code in it (it's much appreciated), but I think that some basic docs would go a long way to help some of us get going. I understand that this framework is aimed at the professional graphics programmer, and that they might be familiar with the general concepts of this type of framework. However, some developers (like myself) are graphic scrubs who don't have much experience with frameworks like Falcor. It would be nice if us scrubs had a chance to hack on Falcor, too. 

I think one of the main benefits of introductory documentation is to take away the feeling of doubt that we might have about whether we're using the framework in a sane way. That is, sometimes, getting something working is not good enough because you might not know if it's built on a house of cards; maybe the code looks like it's working, but it's a timebomb waiting to explode. Some basic intro documentation would help give us confidence, which could translate into code throughput (and thus more idea throughput), because we know we're going about coding the right way. This will help us transition out of the noob phase in less time.

So, from a scrub's perspective, these are some things that I would appreciate to have:
 - A few words about the main systems in the framework, and how they interact with each other.
 - Things to keep in mind for writing performant code. Maybe some do's and dont's.
 - A set of super-basic code examples, with comments in the code. They could be placed in the Samples folder, within a folder named 'StartHere' (or something like that), to make it super obvious. Roughtly, in this order of difficulty:
   1. Hello World Triangle.
   2. Loading a texture into a quad.
    3. Animating the properties of a textured quad (translation, rotation, scale, etc).
    4. An animated texture where the frames of the animation come from an image atlas. This can be used to add detail to a scene without dealing with meshes. Many times, for demos, that's all you need. Think of billboarding background people, off in a distance.
   5. Working with the scene camera.
   6. Quering the scene graph to locate nodes.
   7. Applying some post process effects to a scene.
   8. Loading a simple model (no bones, textures, child nodes, etc) and manipulating some of its properties (translation, rotation, etc).
   9. Loading a textured model that has child nodes, and manipulating those child nodes.
   10. Loading multiple models that have bones and manipulating them via the bones.

The documentation need not be all written in one sitting -- wikis are designed to grow over time. If you (Nv devs) get the ball rolling, it will probably inspire others to fill in the Wiki, too.

Thank you, again, for the wonderful work that you're doing. In time, I hope to learn the framework really well such that I can contribute in possitive manner, hopefully over years to come.

Regards,
Vlad F.

**Comment by nbenty** [comment]
Thanks for the suggestions.
We plan to work on documentation once the Linux port is complete. We will also add some tutorials and samples.

We also accept code contributions, so if you have some samples/snippets I'll be happy to integrate into Falcor.

**Comment by gamagan** [comment]
Thanks for the response.
