### ISSUE TITLE
Any example of stencil and depth test ?

### ISSUE THREAD

**Issue by 625673575** [NVIDIAGameWorks/Falcor#180]
I am try to render an object that have 2 passes,but involve different depth test ,and simply create a new DepthStencilState set with different Desc DepthStencilState::Desc::setDepthFunc(DepthStencilState::Func::Greater); 
is not working at all,and as well the stencil test op,
Is DepthPass class is what I exactly looking for?

**Comment by nbenty** [comment]
Does your depth-buffer have a stencil channel? Falcor defaults to `D32Float` which has no stencil

**Comment by 625673575** [comment]
My idea don't involve depth-buffer or stencil yet,but simply render an object behind anther one in grey is unable. and i ve try almost all permutation.all those things may need a handy example.

**Comment by nbenty** [comment]
If you want to use depth and stencil tests, you need a depth-stencil buffer.
