### ISSUE TITLE
std::make_shared implementation

### ISSUE THREAD

**Issue by angelskieglazki** [NVIDIAGameWorks/Falcor#181]
Hello. Is it possible add this line 
```
GpuTime::SharedPtr GpuTimer::create()
{
    return std::make_shared<GpuTimer>();
}
```
instead this: 
`return SharedPtr(new GpuTimer());`

No doubt you know, these make-functions have slightly better performance, because they cause one new-operator for smart pointer.

But now we need to insert an ugly hack to use these features. Something like this:
```
class GpuTimer : public std::enable_shared_from_this<GpuTimer>
{
**private:
     class Hack {};**
public:
     ... definition GpuTimer::create and SharedPtr...
      **explicit GpuTimer(Hack);**
}
```

I would like to hear your opinion.
regards, Max.

**Comment by nbenty** [comment]
> No doubt you know, these make-functions have slightly better performance, because they cause one new-operator for smart pointer.
I heard that, but if you look at the generated assembly code, you'll see that it's not true (at least not with VS2017)

For `SharedPtr(new GpuTimer()`
```
mov         ecx,50h  
call        operator new (07FFAB3713104h)  
mov         qword ptr [rsp+40h],rax  
mov         rcx,rax  
call        Falcor::GpuTimer::GpuTimer (07FFAB3591900h)  
nop  
xor         ecx,ecx  
mov         qword ptr [rbx],rcx  
mov         qword ptr [rbx+8],rcx  
mov         rdx,rax  
mov         rcx,rbx  
call        std::shared_ptr<Falcor::GpuTimer>::_Setp<Falcor::GpuTimer> (07FFAB3592380h)  
mov         rax,rbx  
```

And `make_shared()`
```
mov         ecx,60h  
call        operator new (07FFAB01031C4h)  
mov         rdi,rax  
mov         qword ptr [rsp+40h],rax  
mov         dword ptr [rax+8],1  
mov         dword ptr [rax+0Ch],1  
lea         rax,[std::_Ref_count_obj<Falcor::GpuTimer>::`vftable' (07FFAB0135A10h)]  
mov         qword ptr [rdi],rax  
lea         rcx,[rdi+10h]  
call        Falcor::GpuTimer::GpuTimer (07FFAAFF81930h)  
nop  
xor         eax,eax  
mov         qword ptr [rsi],rax  
mov         qword ptr [rsi+8],rax  
mov         r8,rdi  
lea         rdx,[rdi+10h]  
mov         rcx,rsi  
call        std::shared_ptr<Falcor::GpuTimer>::_Set_ptr_rep_and_enable_shared<Falcor::GpuTimer> (07FFAAFF82400h)  
mov         rax,rsi  
```

The `SharedPtr()` version is slightly shorter and both version make the same function calls.

Even if that statement was true, I highly doubt that the performance difference would be noticeable. There are other CPU bottlenecks in the code, you'll need to profile to figure out what to optimize.

**Comment by nbenty** [comment]
Actually, after stepping through the assembly `shared_ptr::_Setp` does call `malloc` inside.

However, my last statement still stands - the perf difference is unnoticeable and not worth hacking the code.

**Comment by angelskieglazki** [comment]
Thank you for reply. I will see what I can do in others issues :+1:

**Comment by angelskieglazki** [comment]
> Actually, after stepping through the assembly `shared_ptr::_Setp` does call `malloc` inside.
> 
> However, my last statement still stands - the perf difference is unnoticeable and not worth hacking the code.

Thank you for reply. I will see what I can do in others issues +1
