### ISSUE TITLE
Initialize error 

### ISSUE THREAD

**Issue by cjsb** [NVIDIAGameWorks/Falcor#186]
Hi all,

I am trying to use the code from the course "A Gentle Introduction To DirectX Raytracing" which uses Falco but I am with an issue.

The code compiles but when I try to run the code from the course, a white window appears and them the application closes while it is initializing.

When I debug I got this: 

![image](https://user-images.githubusercontent.com/12685275/54392391-f104f100-467d-11e9-9db2-c6e9ae0a9b79.png)

Anyone knows what might be happening?
Thank you

**Comment by nbenty** [comment]
Is that a release or debug build?

**Comment by cjsb** [comment]
I got the same thing in both configuration.

**Comment by nbenty** [comment]
Which GPU are you using?

**Comment by cjsb** [comment]
RTX 2080. Other rtx samples (the old ones from nvidia) works fine.
