### ISSUE TITLE
Multi layer scene

### ISSUE THREAD

**Issue by cjsb** [NVIDIAGameWorks/Falcor#187]
Hi,

anyone can help me on how to create a multi layer scene on the Falcor framework? I want to choose which part of the scene I am going to ray trace.

Thanks

**Comment by nbenty** [comment]
You'll need to create 2 scenes - one with the meshes you want to raytrace and another scene for raster

**Comment by cjsb** [comment]
nice! and a third one with all together or is there any way I can merge both to use at some point?

**Comment by cjsb** [comment]
nice! 

And a third one with all together or is there any way I can merge both to use at some point? Because I want to ray trace the whole scene but to trace secondary rays for only a parte of the scene.

thank you

**Comment by nbenty** [comment]
In that case you only need 2 scenes - one that contains all the objects and another that only contains the part you need for the secondary rays.

**Comment by cjsb** [comment]
perfect, thank you! =)

**Comment by cjsb** [comment]
Hi again,

I tried to load two scene but I can only use a single one per pass because it goes to the variable gRtScene.

Can I have another gRtScene so I can use both scene in the same pass?
thanks

**Comment by nbenty** [comment]
You can add it yourself. The default is one scene, just change it to an array and initialize it accordingly
