### ISSUE TITLE
All Vulkan Examples fail to run

### ISSUE THREAD

**Issue by fhoenig** [NVIDIAGameWorks/Falcor#188]
Everything seems to compile fine and the samples start up showing a window and a progress bar.
Then random crashes. "ShaderToy" example and a few other crash on some uninitialized std::vector.

The only odd thing I see during build is FalcorSharedObjects spits out a "Access is denied" message. I could not track that one down.

**Comment by nbenty** [comment]
Which OS/GPU/Falcor version are you using?

**Comment by fhoenig** [comment]
Win10, Latest Vulkan, Latest Falcor.
