### ISSUE TITLE
Falcor upgrade process for clients

### ISSUE THREAD

**Issue by gamagan** [NVIDIAGameWorks/Falcor#19]
Hi,

Since the Falcor framework is in beta, I guess this is the best time to bring this up.
I was able to compile the framework into a static lib and bring into my toy engine and get it to display an empty scene (based on the 'ProjectTemplate' sample). 

Based on this exercise, I believe the headers files for Falcor need be in their own include folder. Currently, they are mixed with the cpp files, and they are also located in third-party directories. In order to incorporate  Falcor into my toy engine, I had to restructure some of the Framework directory, move some files about, delete non-header files, and edit one or two headers to repoint their #include directives. 

My wish is to stay up-to-date with the latest version of Falcor whenever a new version is released to Github. Having to manually rearrange the code, like I did this first time, is error prone. It makes me nervous just thinking about it.

IMO, it would be ideal if upgrading to a newer version of Falcor were this easy:
 1. Update to Falcor HEAD: git pull origin master
 2. Build Falcor
 3. Copy the Falcor.lib (and others?) and an include directory to my toy engine.

If it were this easy, then this would allow me to automate the process down to calling a single script. That would be sweet.

Regards,
Vlad F

**Comment by gamagan** [comment]
I want to add,

It would also be nice to know which non-header files are the actual dependencies for the framework. Specifically:
 - If we have all the Falcor headers within one 'include' directory, then it's implied that all headers in that directory, and sub directories, are required to link against Falcor. But, if there are headers outside of that 'include' dir, then they shouldn't be required to link against Falcor.
 - Which .lib/.dll files are needed to link and run the framework. Perhaps, some libs are needed only while building Falcor, but are not needed thereafter.
 - What is the relationship to the "Data" directory at runtime. The Data dir has some subdirs.

Finally, holy molly! Falcor.lib is 178MB!

Regards,
Vlad F

**Comment by nbenty** [comment]
Hi Vlad,
Thanks for the comments.
* I can't move the external include directories to a common include folder. License stuff.
* We plan to stop using DLLs and switch to static libraries. That should make the executable self-contained which should simplify sharing samples.
* Copying the headers is not enough. There are also some shader files and shader headers that need to be copied.
* I have no idea why the debug version of Falcor.lib is 178MB. I'll need to look into that.

Anyway, it's a bit more complicated than a single include directory. We will add a script that packages everything you need to use Falcor.

**Comment by gamagan** [comment]
> Anyway, it's a bit more complicated than a single include directory. We will add a script that packages everything you need to use Falcor.

That is swell! Thank you.

**Comment by nbenty** [comment]
@clavelleNV The required process is similar to the one you went through with the DxrSample. Please create a script which will:
- Build Falcor.lib (configuration should be specified by the user)
- Pack everything required to run Falcor (lib, headers, shaders, property sheet, post-build scripts)

Make sure the package generated can be used to create a standalone sample.
This can wait until after 3.0 is ready
