### ISSUE TITLE
Get bouding box information

### ISSUE THREAD

**Issue by cjsb** [NVIDIAGameWorks/Falcor#190]
Hi,

is there any way of getting the bounding box information of a hit object? I can't find this information on the ShadingData.

Thanks

**Comment by nbenty** [comment]
Which bounding box are you referring to?
If you want the bounding box from the TLAS, the DXR API doesn't expose it.

If you want the bounding-box Falcor computes in and stores in `Mesh`, we don't pass it to the shader, but you can add it yourself quite easily. Just add the fields to `InternalPerMeshCB` and assign the value in `SceneRenderer::setPerMeshData()`

**Comment by cjsb** [comment]
Cool.

I am using the Model::LoadFlags::DontMergeMeshes flag but it gets slow. If I merge the scene it gets fast but I can't access each model individually. Is there any way I can get the bounding box of the object without the merge?

**Comment by nbenty** [comment]
We pass the flag into ASSIMP, the meshes we get are pre-processed and we have no idea how the original meshes looked like.

It also doesn't make much sense to store the original box - since meshes are merged into a single geometry there will be multiple original boxes per new-mesh. You'll have to use the primitive ID to identify the original mesh and fetch the matching BBOX, which is costly.

**Comment by cjsb** [comment]
Got it. But why it gets slow when I use the  Model::LoadFlags::DontMergeMeshes flags? It goes from 100 fps to 4 fps.

**Comment by nbenty** [comment]
Whatever asset you're loading, I guess it's not optimized. 
The more meshes you have, the larger the TLAS will be. Merging meshes means fewer BLASs and a more optimized TLAS.

There are other inefficiencies when using a lot of small meshes - the SBT is much larger, increasing the CPU overhead, etc.

**Comment by cjsb** [comment]
I see. I was thinking of how to get this information.
 
If I create the scene by hand instead of loading from a fbx (my scene only has simple primitives) and I keep the center of the bounding information of the object on the triangles, can I get this info from the shader?
I know that it will increase the memory but it was a way of getting the information that I need.

**Comment by nbenty** [comment]
There are 2 options:
(a) Edit the asset in Maya/3DS/Blender/whatever. You can manually optimize the mesh layout there in a way that makes the loader optimization redundant. If you're going this route then you can just pass the bounding boxes into the shader.
(b) Create a custom data structure in you application or create the scene by hand. If you're scene is simple 

Both options will work. Choose based on what you are most comfortable with. I would probably go with (a)

**Comment by cjsb** [comment]
Thanks!

Do you have a maximum number of meshes that I can have to a good performance (not doing some fancy shaders right now)? Because I don't have a huge scene. 

Also, my scene is not changing in time. By any change the BVH is being reconstructed in every frame? Because that would use a lot of my budget.

**Comment by nbenty** [comment]
There's an issue where if the camera is attached to a path, the BVH will be reconstructed every frame. I'm working on fixing it, but if you are not using camera paths you shouldn't worry about it. From my experience building the BVH is quite fast - around 1ms for a complex scene.

I don't have a number of meshes... We're using large scenes (Bistro and Emerald-Square from ORCA) without issues. You'll need to experiment with it.

**Comment by cjsb** [comment]
got it! Thank you very much for the help! =)
