### ISSUE TITLE
Loading Bistro scene on SceneEditor issues..

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Falcor#2]
Hi,
testing Bistro scene on Falcor 2.0 beta SceneEditor I see:

*Direct3D12 seems a lot slower than Vulkan although you say D3D12 is lot more optimized:
Bistro interior scene: On a GTX970 I get 70fps on Vulkan and 25fps on D3D12 backend..
(using 382.88 Siggraph driver)

*Even compiling release mode SceneEditor needs lots of RAM for loading scenes:
I have a PC with 32GB RAM and SceneEditor fails silently to load (program exits) Bistro exterior scene when this process uses around 20GB of RAM.. haven't debugged yet to see where it fails but sounds like needs either more GPU VRAM (4gb VRAM) or CPU RAM..

*also seems SceneEditor on D3D12 can enter full screen with Alt+Enter but not on Vulkan (this is a minor issue but just commenting it..

**Comment by nbenty** [comment]
* The FeatureDemo runs faster in D3D12 then in Vulkan. Not sure why the SceneEditor is slower, I'll take a look.
* The Bistro assets has 2K uncompressed textures. I'm not sure 4GB VRAM is enough when you consider all the mip-levels requires etc. We are working on a version of the bistro that will use compressed formats, that should reduce the memory requirements.

* I'll take a look at the fullscreen issue.

Thanks for reporting!

**Comment by nbenty** [comment]
Closing this issue. We are about to release a new version of the Bistro with compressed textures that should run much faster
