### ISSUE TITLE
Some ETA for "Importance Sampling of Many Lights on the GPU" code part of Falcor 4.0 code?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Falcor#202]
Hi,
just seen Ray Tracing Gems source code and 
"Ch_18_Importance_Sampling_of_Many_Lights_on_the_GPU" readme shows:
```
"Importance Sampling of Many Lights on the GPU"
The code repository for the article will be a part of [Falcor 4.0](https://github.com/NVIDIAGameWorks/Falcor) when it becomes available.  
```
so just asking if ETA can be shared of Falcor 4.0 or at least when some commits supporting "Importance Sampling of Many Lights on the GPU" feature will be committed..
maybe for Siggraph 2019 next month we will have this support?
thanks..

**Comment by nbenty** [comment]
We plan to release Falcor 4.0 around October.
We probably won't be releasing anything before that.

**Comment by Reon90** [comment]
Hi,
Falcor 4.0 has been already released. What about plans on Chapter 18th?

**Comment by kyaoNV** [comment]
They are the "LightBVH" files located in `Source/Falcor/Experimental/Scene/Lights/`. 

`LightBVH` should also be the default emissive sampler when you run the Path Tracer render graphs.
