### ISSUE TITLE
StructuredBufferSrv mapped to wrong descriptor type in Vulkan

### ISSUE THREAD

**Issue by philcn** [NVIDIAGameWorks/Falcor#203]
This is a bug that I ran into very early on but was only confirmed today:

cpp:
```
mStructuredBuffer = StructuredBuffer::create(mProgram, "gMyBuffer", 4);
std::vector<vec4> data = { vec4(0, 0, 0, 1), vec4(1, 0, 0, 1), vec4(0, 1, 0, 1), vec4(0, 0, 1, 1) };
mStructuredBuffer ->setBlob(data.data(), 0, data.size() * sizeof(data[0]));
mVars->setStructuredBuffer("gMyBuffer", mStructuredBuffer);
```

Shader:
```
StructuredBuffer<float4> gMyBuffer;

float4 mainPS() : SV_TARGET
{
    return gMyBuffer[1];
} 
```

This code is supposed to just work (and it works in D3D12). However, I'm getting the following error (and reading the structured buffer from shader returns 0)

```
FalcorVK Error:  [ UNASSIGNED-CoreValidation-Shader-DescriptorTypeMismatch ] Object: VK_NULL_HANDLE (Type = 0) | Type mismatch on descriptor slot 0.1 (expected `VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC`) but descriptor of type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
```

I found that in VKDescriptorPool.cpp, falcorToVkDescType() returns VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER for StructuredBufferSrv. Since slang emits "readonly buffer { ... }" instead of "uniform { ... }" for StructuredBuffer<T>, I think the mapping should return VK_DESCRIPTOR_TYPE_STORAGE_BUFFER instead. This does fix the problem from what I can tell.

**Comment by nbenty** [comment]
Thanks. I fixed it in my 4.0 dev branch
