### ISSUE TITLE
No easy way to bind a Falcor::Buffer as a TypedBuffer (Buffer<T>) in Vulkan

### ISSUE THREAD

**Issue by philcn** [NVIDIAGameWorks/Falcor#204]
In Vulkan, if your program owns a Falcor::Buffer, and you want to access it from shader, the only way right now is to bind it as a StructuredBuffer<T> / RWStructuredBuffer<T>. If I want to use Buffer<T> in shader, since the DescriptorSet code can't create the uniform texel buffer view from a Falcor::Buffer, I have to re-create the buffer as Falcor::TypedBuffer<T> instead.

This is inconvenient when I just want to bind a buffer that my code doesn't own. For example, binding VB/IB for ray tracing. I'd like this to be improved, and I can think of two ways:

1. When binding a Falcor::Buffer to typed buffer (uniform texel buffer), infer the type from reflection. 

2. Add a path to "cast" the Falcor::Buffer into Falcor::TypedBuffer<T> without making them two distinct buffers, this means redesigning the TypedBuffer class as a "view" into the Buffer.

Do you think this is a legit use case and would like to accommodate?

**Comment by nbenty** [comment]
For 4.0 we are getting rid of `StructuredBuffer`, `TypedBuffer` and `ConstantBuffer`. There will only be a buffer that you can bind as a structred/typed/constant or raw buffer.

If you are blocked, implementing it yourself is starightforward. It mostly requires you to remove some type checks in the code.

**Comment by philcn** [comment]
That sounds good; as long as the mesh VB/IB are going to use the only remaining buffer class you're talking about I'm sure it'll solve my problem. I can get by with using StructuredBuffer<T> in shader for now. Thanks
