### ISSUE TITLE
Question: No Object File generated

### ISSUE THREAD

**Issue by Jaliborc** [NVIDIAGameWorks/Falcor#208]
Fresh Falcor install. Using Microsoft Visual Studio on Windows 10. All build modes result in the error: 

> warning treated as error - no object file generated (compiling source file Utils/Platform/Windows/Windows.cpp)

Anyone knows what might cause this?

**Comment by nbenty** [comment]
Can you post the entire log?
There should be a warning message before the error

**Comment by Jaliborc** [comment]
Here is the full log. The result is the same with other build modes (DebugVK, DebugD3D12, etc).

> 1>------ Build started: Project: FalcorSharedObjects, Configuration: ReleaseVK x64 ------
> 1>Setting user environment variable PM_PACKAGES_ROOT to C:\packman-repo
> 1>
> 1>SUCCESS: Specified value was saved.
> 1>Processing project file 'C:\Users\jaliborc\Documents\variable-rate-shading\falcor\dependencies.xml'
> 1>imgui.cpp
> 1>imgui_demo.cpp
> 1>imgui_draw.cpp
> 1>imgui_widgets.cpp
> 1>imguinodegrapheditor.cpp
> 1>FalcorSharedObjects.cpp
> 1>   Creating library C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Bin\x64\Release\FalcorSharedObjects.lib and object C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Bin\x64\Release\FalcorSharedObjects.exp
> 1>Generating code
> 1>Previous IPDB not found, fall back to full compilation.
> 1>All 1856 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
> 1>Finished generating code
> 1>FalcorSharedObjects.vcxproj -> C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Bin\x64\Release\FalcorSharedObjects.dll
> 2>------ Build started: Project: Falcor, Configuration: ReleaseVK x64 ------
> 2>glm.cpp
> 2>BlendState.cpp
> 2>Buffer.cpp
> 2>ComputeContext.cpp
> 2>ComputeStateObject.cpp
> 2>CopyContext.cpp
> 2>DepthStencilState.cpp
> 2>DescriptorSet.cpp
> 2>Device.cpp
> 2>FBO.cpp
> 2>Formats.cpp
> 2>GpuTimer.cpp
> 2>DescriptorPool.cpp
> 2>ResourceAllocator.cpp
> 2>RootSignature.cpp
> 2>GraphicsStateObject.cpp
> 2>RenderContext.cpp
> 2>Resource.cpp
> 2>ResourceViews.cpp
> 2>Sampler.cpp
> 2>StructuredBuffer.cpp
> 2>Texture.cpp
> 2>ConstantBuffer.cpp
> 2>TypedBuffer.cpp
> 2>VAO.cpp
> 2>VariablesBuffer.cpp
> 2>VKComputeStateObject.cpp
> 2>VkQueryHeap.cpp
> 2>Window.cpp
> 2>ArgList.cpp
> 2>SSAO.cpp
> 2>FXAA.cpp
> 2>LeanMap.cpp
> 2>ParticleSystem.cpp
> 2>CSM.cpp
> 2>SkyBox.cpp
> 2>TAA.cpp
> 2>ToneMapping.cpp
> 2>GaussianBlur.cpp
> 2>RenderPass.cpp
> 2>RenderGraph.cpp
> 2>RenderGraphImportExport.cpp
> 2>RenderGraphIR.cpp
> 2>RenderGraphScripting.cpp
> 2>RenderGraphUI.cpp
> 2>RenderPassLibrary.cpp
> 2>RenderPassReflection.cpp
> 2>ResourceCache.cpp
> 2>BlitPass.cpp
> 2>DepthPass.cpp
> 2>ForwardLightingPass.cpp
> 2>ImageLoader.cpp
> 2>ResolvePass.cpp
> 2>Camera.cpp
> 2>CameraController.cpp
> 2>ComputeState.cpp
> 2>FboHelper.cpp
> 2>FullScreenPass.cpp
> 2>Light.cpp
> 2>LightProbe.cpp
> 2>Material.cpp
> 2>Animation.cpp
> 2>AnimationController.cpp
> 2>AssimpModelImporter.cpp
> 2>BinaryImage.cpp
> 2>BinaryModelExporter.cpp
> 2>BinaryModelImporter.cpp
> 2>ModelImporter.cpp
> 2>SimpleModelImporter.cpp
> 2>Mesh.cpp
> 2>Model.cpp
> 2>ModelRenderer.cpp
> 2>SkinningCache.cpp
> 2>ObjectPath.cpp
> 2>PathEditor.cpp
> 2>GraphicsState.cpp
> 2>ComputeProgram.cpp
> 2>GraphicsProgram.cpp
> 2>ParameterBlock.cpp
> 2>Program.cpp
> 2>ProgramReflection.cpp
> 2>ProgramVars.cpp
> 2>ProgramVersion.cpp
> 2>ShaderLibrary.cpp
> 2>SceneEditor.cpp
> 2>SceneEditorRenderer.cpp
> 2>Scene.cpp
> 2>SceneExporter.cpp
> 2>SceneImporter.cpp
> 2>SceneRenderer.cpp
> 2>TextureHelper.cpp
> 2>Sample.cpp
> 2>UnitTest.cpp
> 2>Bitmap.cpp
> 2>DebugDrawer.cpp
> 2>DXHeader.cpp
> 2>Font.cpp
> 2>Gui.cpp
> 2>Logger.cpp
> 2>ParallelReduction.cpp
> 2>MonitorInfo.cpp
> 2>DxSamplePattern.cpp
> 2>HaltonSamplePattern.cpp
> 2>Picking.cpp
> 2>PixelZoom.cpp
> 2>OS.cpp
> 2>ProgressBar.cpp
> 2>ProgressBarWin.cpp
> 2>Windows.cpp
> 2>Profiler.cpp
> 2>Experiment.cpp
> 2>SingleThresholdMeasurement.cpp
> 2>PythonEmbedding.cpp
> 2>Scripting.cpp
> 2>ScriptBindings.cpp
> 2>TextRenderer.cpp
> 2>VariablesBufferUI.cpp
> 2>VideoDecoder.cpp
> 2>VideoEncoder.cpp
> 2>VideoEncoderUI.cpp
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2308,23): error C2220:  warning treated as error - no 'object' file generated (compiling source file Utils\Platform\Windows\Windows.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :  see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :         with
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :         [
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :             _Iter=wchar_t *
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :         ] (compiling source file Utils\Platform\Windows\Windows.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :  see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :         with
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :         [
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :             _Iter=wchar_t *
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2319): message :         ] (compiling source file Utils\Platform\Windows\Windows.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :  see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :         with
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :         [
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :             _Iter=wchar_t *
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :         ] (compiling source file Utils\Platform\Windows\Windows.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :  see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :         with
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :         [
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :             _Iter=wchar_t *
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2299): message :         ] (compiling source file Utils\Platform\Windows\Windows.cpp)
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :  see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,void>(_Iter,_Iter,const _Alloc &)' being compiled
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :         with
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :         [
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :             _Elem=wchar_t,
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :             _Iter=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :             _Alloc=std::allocator<char>
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :         ]
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :  see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,void>(_Iter,_Iter,const _Alloc &)' being compiled
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :         with
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :         [
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :             _Elem=wchar_t,
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :             _Iter=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :             _Alloc=std::allocator<char>
> 2>C:\Users\jaliborc\Documents\variable-rate-shading\falcor\Framework\Source\Utils\Platform\Windows\Windows.cpp(485): message :         ]
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2308,23): warning C4244:  'argument': conversion from 'wchar_t' to 'const _Elem', possible loss of data
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2308,23): warning C4244:         with
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2308,23): warning C4244:         [
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2308,23): warning C4244:             _Elem=char
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xstring(2308,23): warning C4244:         ] (compiling source file Utils\Platform\Windows\Windows.cpp)
> 2>Done building project "Falcor.vcxproj" -- FAILED.
> ========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
>

**Comment by nbenty** [comment]
Try updating your compiler. I think we require Visual Studio 2017 version 15.9.x (Help->About will show you the version, and Help->Check for updates will update it)

**Comment by Jaliborc** [comment]
Tried updating just to double-check, but I am running the current latest version 16.2.1.
Is that not compatible?

**Comment by nbenty** [comment]
Oh, you're on VS 2019.
We never tried using 2019, so I don't know if something changed there in a way that is incompatible with our project files.

I suggest you stick to VS 2017 as this is the version we are using internally.

**Comment by Jaliborc** [comment]
Will try that then

**Comment by Jaliborc** [comment]
That worked. Thank you for the help.
