### ISSUE TITLE
Default values for min and max for Gui::addFloat*Slider assert in ImGui

### ISSUE THREAD

**Issue by Qbz23** [NVIDIAGameWorks/Falcor#210]
Pretty minor issue, but it seems like Falcor's Gui wrapper uses -/+ FLT_MAX for default min and max values. However, in imgui_widgets.cpp, ImGui::SliderBehavior asserts that min/max values must fall in the range of -/+ FLT_MAX/2.0f. 

Comment on relevant ImGui function...
// For 32-bits and larger types, slider bounds are limited to half the natural type range.

**Comment by nbenty** [comment]
Thanks, I didn't notice that.
We'll fix it in 4.0
