### ISSUE TITLE
getGGXMicrofacet() handles roughness remapping wrong

### ISSUE THREAD

**Issue by philcn** [NVIDIAGameWorks/Falcor#212]
According to Karis 14, the standard GGX importance sampling formula is:

```
float a = roughness * roughness;
float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a * a - 1.0) * Xi.y));
```

Here, the "roughness" variable is supposed to be the perceptual linear roughness value, the value that artists work on.

This is confirmed by the 2012 Disney PBS Notes,

```
For roughness, we found that mapping α = roughness2 results in a more perceptually linear change in the roughness. Without this remapping, very small and non-intuitive values were required for matching shiny materials. Also, interpolating between a rough and smooth material would always produce a rough result. 
```

However, in Falcor, the getGGXMicrofacet() method is called with sd.roughness, then the following cosTheta is computed:

```
// roughness is Roughness^2 of material
float3 getGGXMicrofacet(float2 u, float3 N, float roughness) {
float a2 = roughness * roughness;
float cosTheta = sqrt(max(0, (1 - u.y)) / (1 + (a2 * a2 - 1) * u.y));
```

This produces wrongly sampled half vectors. To fix this and adhere to the correct terminology, the above code should either become:

```
// a (alpha) is Roughness^2 of material, i.e. sd.roughness
float3 getGGXMicrofacet(float2 u, float3 N, float a) {
float cosTheta = sqrt(max(0, (1 - u.y)) / (1 + (a * a - 1) * u.y));
```

or

```
// roughness is Roughness^2 of material
float3 getGGXMicrofacet(float2 u, float3 N, float roughness) {
float a2 = roughness * roughness;
float cosTheta = sqrt(max(0, (1 - u.y)) / (1 + (a2 - 1) * u.y));
```

or 

```
// linearRoughness is sd.linearRoughness
float3 getGGXMicrofacet(float2 u, float3 N, float linearRoughness) {
float a = linearRoughness * linearRoughness;
float cosTheta = sqrt(max(0, (1 - u.y)) / (1 + (a * a - 1) * u.y));
```

The evalSmithGGX() and evalGGX() functions are correct; they take sd.roughness and calculate a2 as sd.roughness * sd.roughness.

IMO, it'd be better to use sd.roughness for the perceptually linear roughness and use sd.alpha for the remapped roughness (GGX parameter), or completely get rid of the old sd.roughness, since many implementations have different roughness-to-alpha mapping for different BRDF terms.

**Comment by nbenty** [comment]
That function is gone Falcor 4.0.
We'll be releasing a bunch of material sampling helper routines which we ran tests on to confirm that they are accurate and as close as possible to the ground truth.

**Comment by philcn** [comment]
Thanks for letting me know.

How about my suggestion of changing the naming of (linearRoughness, roughness) into (roughness, ggxAlpha) to avoid confusion?

**Comment by nbenty** [comment]
We're changing it as well
