### ISSUE TITLE
Don't saturate() the specular BRDF

### ISSUE THREAD

**Issue by philcn** [NVIDIAGameWorks/Falcor#214]
A very subtle bug, in https://github.com/NVIDIAGameWorks/Falcor/blob/master/Framework/Source/ShadingUtils/Shading.slang#L370, saturating the BRDF can lead to distortion of the specular highlight. A potential fix is to use max(0.0, brdf).

Before:
![Screenshot_20190910_182404](https://user-images.githubusercontent.com/2667822/64662014-c2cd5780-d3fb-11e9-946b-5088ed9c1ee6.png)

After:
![Screenshot_20190910_182351](https://user-images.githubusercontent.com/2667822/64662028-d11b7380-d3fb-11e9-9a03-79d7ce101251.png)

**Comment by nbenty** [comment]
This one is already fixed in my dev branch.
Good catch though, this one was tricky.
