### ISSUE TITLE
Failed to compile with visual studio 2019

### ISSUE THREAD

**Issue by gobaya111** [NVIDIAGameWorks/Falcor#223]
class RtShader is privately inherited form the inherit_shared_from_this class. The code failed to be compiled in Visual studio, with the following error message:
D:\Falcor-master\Source\Falcor\Core\Framework.h(231,1): error C2243: 'static_cast': conversion from 'const Falcor::inherit_shared_from_this<Falcor::Program,Falcor::ComputeProgram> *' to 'const Derived *' exists, but is inaccessible
This issue can be fixed by change the inheritance to public:
class dlldecl RtShader : public Shader, public inherit_shared_from_this<Shader, RtShader>.
The same issues in other class can be fixed in the same way.

**Comment by FishOrBear** [comment]
yep
