### ISSUE TITLE
Falcor 4 for linux and vulkan

### ISSUE THREAD

**Issue by KaChen-Dex** [NVIDIAGameWorks/Falcor#229]
Hi,
The readme of Falcor 4 only mentions supporting for DX12. Is vulkan or linux going to be supported like in Falcor 3? thanks.

**Comment by kyaoNV** [comment]
Our priority for Falcor 4 was DXR and raytracing features, and we did not have the resources to support other platforms. Linux/Vulkan isn't officially gone for good, but we're still figuring out when/if it will return.
