### ISSUE TITLE
RenderGraph & Falcor Application Workflow

### ISSUE THREAD

**Issue by MartinMisiak** [NVIDIAGameWorks/Falcor#230]
Is the rendering graph in Falcor 4.0 intended only for the "Mogwai workflow" or can it easily be also used in the "falcor application workflow" ? I'm asking, as none of the sample applications are using it and the documentation regarding this is currently not present.

**Comment by kyaoNV** [comment]
Render graphs are mostly intended for using with Mogwai and scripting, but you should be able to use them elsewhere. There's a simple example of this in `SSAO.cpp` where a render graph is created for blurring.
