### ISSUE TITLE
InvalidPixelDetectionPass test failed.

### ISSUE THREAD

**Issue by xin-xinhanggao** [NVIDIAGameWorks/Falcor#232]
Hi, I could build Falcor correctly with VS2019. However, it seems that  InvalidPixelDetectionPass test failed like this:

  InvalidPixelDetectionTests.cpp/InvalidPixelDetectionPass (GPU): FAILED (3 ms)
    Could not create render pass 'InvalidPixelDetectionPass'
 
Could I do something to fix it?  And will this failed pass have a negative impact?

**Comment by kyaoNV** [comment]
That might be because the whole solution wasn't built. The render pass projects aren't built by default if you just build Falcor or Mogwai, and that test references one of those.

**Comment by Donsome** [comment]
I encountered the same problem when compiling version 4.2
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/45633064/5d3afeb1-28f2-4a16-9f6c-eaec33bd72e1)
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/45633064/348d5b5a-df40-4b81-bf2e-d4576aff7296)
