### ISSUE TITLE
CudaInterop sample and type collisions

### ISSUE THREAD

**Issue by darrelpalke** [NVIDIAGameWorks/Falcor#235]
With the 4.1 update, the CudaInterop project no longer compiles (after manually including in the solution and having cuda dependencies locally installed).  The fix is very simple, add Falcor:: to the clear color definition.

But this brings up a bigger issue.  If you intend to include cuda.h (or actually cuda_runtime.h) in any of your Falcor code and do interop, it forces you to resolve all usages of the internal Falcor vector types with a namespace to avoid 'ambiguous symbol' errors in Visual Studio.  The same names are used here.

I see that there is another previous issue that likely brought about this change, whereby using float3 already had issues with cuda and glm collisions due to the compat header.  Now its just a bit worse.  We have 3 types ::float3, Falcor::float3 and glm::float3 and they are all ambiguous without any namespace.  

I feel like using glm types directly was the cleaner thing overall.  There is already usage of glm::inverse and other things right next to these Falcor types in the sample code anyway and glm is widely used in the open source community.

Is the better solution to revert back to glm types and then just not include the compat header from them?  I'm not sure if that header is used anywhere in the code.

**Comment by kyaoNV** [comment]
Thanks for catching this, although there shouldn't be a collision with `glm::float3` since we've removed `glm` from the `Falcor` namespace.

The goal is to eventually move away from GLM to an implementation that matches the matrix conventions of Slang/HLSL.

Filed as internal issue #854
