### ISSUE TITLE
Where did the Vulkan / Linux support go?

### ISSUE THREAD

**Issue by tripleslash** [NVIDIAGameWorks/Falcor#239]
In an earlier version of Falcor the README used to say that it supports Vulkan and Ubuntu. Is this now officially dropped for DirectX 12 only? Because there are still Vulkan Source Files to be found in the Code (is this dead code?).

Thanks!

**Comment by vinjn** [comment]
I think it's dead.

**Comment by skallweitNV** [comment]
Vulkan support just came back with the new GFX backend. It's still experimental and not fully done yet. Bringing back Linux support is on the roadmap as well.
