### ISSUE TITLE
Build error in Windows 10, Visual Studio 2019

### ISSUE THREAD

**Issue by pnt1614** [NVIDIAGameWorks/Falcor#241]
I am trying to build the Falcor in Windows 10 with Visual Studio 2019 but there is an error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	the following warning is treated as an error	Falcor	D:\project\BVH\Two-level_BVH\Falcor\Source\Externals\.packman\pybind11\include\pybind11\detail\common.h	1	

Even if I turned off "Treat Warnings As Errors" in the project properties

**Comment by skallweitNV** [comment]
We've came across this as well, it's a rare condition with the MSVC compiler we can't really reproduce. However, there is a workaround that is enabled with the latest 5.1 release.

**Comment by bipul-mohanto** [comment]
In MSVS2022, the same problem is found in the `Debug` build, but the `Release` is okay. A solution like `Treat warnings as errors" from "All" to "Specific warnings" or "None"` is not working. The main problem in `format.h` line 559 `template <typename T> using checked_ptr = stdext::checked_array_iterator<T*>;`

Any suggestion?
