### ISSUE TITLE
Several errors in tutorial 4

### ISSUE THREAD

**Issue by b1skit** [NVIDIAGameWorks/Falcor#242]
I'm a new Falcor user, and I've noticed several issues in the 4th tutorial ("Writing Shaders") that mean the tutorial does not work as written. Running a copy/paste of the tutorial code results in Mogwai crashing with no error message.

Here are the issues, and their solutions:

1) In the execute() function, the mpVars pointer is garbage until it is assigned a value in setScene(). mpVars should be initialized to null in the .h file, and null-checked before it is accessed in the execute() function.

2) At the end of the tutorial, it states you don't need to load a scene as Mogwai will load the arcade scene by default. This is not true; you must load a scene manually. This will trigger the call to setScene(), which will initialize the mpVars pointer so we can access it in the execute() function.

Hope this helps!

**Comment by kyaoNV** [comment]
Thanks for the report! We'll get that updated.
