### ISSUE TITLE
Assert hit when loading ForwardRenderer.py in Mogwai

### ISSUE THREAD

**Issue by kseitz** [NVIDIAGameWorks/Falcor#243]
Hello,

Falcor is hitting an assert when I use Mogwai to load the [ForwardRenderer.py](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Source/Mogwai/Data/ForwardRenderer.py) render graph script.  I am following the instructions from [Getting-Started.md](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Docs/Getting-Started.md) under Workflows -> Render Graphs -> To run a sample Render Graph.  

This issue occurs both when loading the script first, as well as when loading a scene first.  I tried the following [ORCA](https://developer.nvidia.com/orca) scenes: EmeraldSquare_Day.py, EmeraldSquare_Day.fbx, SunTemple.fscene, BistroInterior.fbx, and BistroInterior_Wine.py.

**Debugging information:**

- The assert is in [HitInfo.h](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Source/Falcor/Scene/HitInfo.h) on [line 57](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Source/Falcor/Scene/HitInfo.h#L57)
- On that line, `instanceIndexBits` is 0, which fails the `instanceIndexBits > 0` check.
- `instanceIndexBits` gets assigned to 0 on [line 46](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Source/Falcor/Scene/HitInfo.h#L46), because `maxInstanceID` is 0.
- `maxInstanceID` gets assigned to 0 on [line 45](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Source/Falcor/Scene/HitInfo.h#L45) because `meshInstanceCount` is 1.
- `meshInstanceCount` gets assigned based on the scene passed as an argument to this function

I would think that a `meshInstanceCount` of 1 would be valid, so I do not know how to continue debugging from here.

**Other information:**

- Falcor Commit: https://github.com/NVIDIAGameWorks/Falcor/commit/57e3d42a8656e0f5933e8b04a2d30be320c8c831 (Falcor 4.1; currently top-of-tree)
- Build Configuration: DebugD3D12*
- NVAPI: enabled
- GPU: NVIDIA GTX 1080

I will appreciate help in fixing this issue.  If there is any other info I can provide, please let me know!

Thanks,
Kerry

*The assert is, of course, not hit when using ReleaseD3D12.  However, the scenes do not seem to be rendering properly.  There is horrible flickering/incorrect lighting, as well as issues with shadows (for example).  I'm not sure if the rendering issues are related to the assert or not.  Running the Debug configuration and commenting out the assert results in the same issues.  Various issues occur with all of the scenes mentioned above.

**Comment by kyaoNV** [comment]
Thanks for the detailed report! Looks like this has already been fixed internally. [The assert in question](https://github.com/NVIDIAGameWorks/Falcor/blob/57e3d42a8656e0f5933e8b04a2d30be320c8c831/Source/Falcor/Scene/HitInfo.h#L57) is incorrect and should be removed. The next release will include this change.
