### ISSUE TITLE
Mogwai crashes when you press F12 to take a screenshot

### ISSUE THREAD

**Issue by b1skit** [NVIDIAGameWorks/Falcor#247]
Repro steps:

1) Launch Mogwai via Visual Studio
2) Load your desired script
3) Load your desired scene (eg. Arcade.fscene)
4) Press F12 to take a screenshot

Mogwai crashes with "Mogwai.exe has triggered a breakpoint." in the output logs. I can't debug it any further, as I'm getting "Source Not Available" in Visual Studio when this happens.

Maybe I'm missing something here, as this seems like someone would have noticed this by now. Am I screwing up something, or is this a known issue?

**Comment by Qbz23** [comment]
F12 is the default key to break in visual studio. You could either run without debugger attached or probably change the key bind

**Comment by b1skit** [comment]
Ah that would explain it - thank you!
