### ISSUE TITLE
GPU Selection will select an iGPU instead of an available dGPU with Raytracing

### ISSUE THREAD

**Issue by awr1** [NVIDIAGameWorks/Falcor#252]
On trying the HelloDXR sample, I got this error message:

![image](https://user-images.githubusercontent.com/41453959/90970521-df0ebb00-e4cb-11ea-8d6c-cb6576beba6f.png)

I use a laptop with a dedicated RTX 2060 Max-Q GPU with a fallback integrated AMD Vega GPU. Upon closer inspection, the culprit lies in `D3D12Device.cpp` in `Falcor::createDevice()`, on enumerating through the available devices an adapter is immediately picked if it meets the basic feature level requirements instead of holding off and continuing the enumeration process to see if there is a better adapter to use on the system. In my case, the first adapter that gets enumerated is the Vega, which has no DXR support, ergo I cannot launch the examples.

**Comment by kyaoNV** [comment]
4.2 now defaults to selecting an NVIDIA GPU when available. If you want to select others, there's a couple environment variables `createDevice()` checks that are described [here](https://github.com/NVIDIAGameWorks/Falcor/blob/master/Docs/Usage/Environment-Variables.md).
