### ISSUE TITLE
The frame rate drops dramatically when the scene is animated

### ISSUE THREAD

**Issue by b1skit** [NVIDIAGameWorks/Falcor#260]
As the title suggests, if scene animation is enabled, the frame rate drops dramatically.

Pausing the global timer (by pressing spacebar), or toggling the "Scene Settings -> Animate Scene" checkbox fixes the problem, and the frame rate jumps up to ~9ms per frame.

When the issue is occurring, capturing a sequence of frames using PIX shows each successive frame is rendering in ~9ms, yet the Mogwai UI captured in those same frames shows each frame rendering in ~400ms. 

This occurs with all of the included sample passes I have tested (eg. the Whitted Ray Tracer render pass). It also occurs with all of the ORCA sample scenes with animated scenes/cameras that I have tested.

I've uploaded a screenshot of the PIX capture showing the behavior here: 
https://ibb.co/K0D43Jw
I captured a sequence of 5 frames. Notice, each frame rendered in ~9ms each, yet Mogwai reports each frame taking ~397ms (and the performance is TERRIBLE!). 

It feels like Mogwai is accurately reporting the frame rate, but there is some huge slowdown occurring for some reason.

Any idea what's going on? This seems like such an obvious bug that I can't be the first person to encounter it... Am I missing something/screwing something up? Appreciate any insight or help!

Edit: I've noticed that if I disable the camera animation via the GUI (enabling free-cam mode), the frame rate immediately jumps up much higher. Re-enabling the camera animation causes the frame rate to drop again. This definitely seems to be a bug

**Comment by cuteday** [comment]
Hey, although it's been a while, but have you switch the build config from DebugD3D to ReleaseD3D? If not, you can try it. I guess the real time consuming part contains in the c++ code.

**Comment by skallweitNV** [comment]
There are some performance issues with the animation system, they are much pronounced in debug builds. We will be working on improving this in the near future.
