### ISSUE TITLE
OpenVR Support For Current Version？

### ISSUE THREAD

**Issue by Bob-Yeah** [NVIDIAGameWorks/Falcor#261]
I’m considering why OpenVR support is deprecated at Falcor4.2. Is it possible you guys will add this feature back? Otherwise I have to go through the source code of Falcor3.2 and do it myself...

**Comment by kyaoNV** [comment]
VR is currently not a priority for us and we do not have the resources to support it. I do not know if/when VR support will return.

**Comment by bipul-mohanto** [comment]
@kyaoNV , sorry to ask, does it mean also Falcor 4.4 not supported by OpenVR?

**Comment by bipul-mohanto** [comment]
Hi @kyaoNV, so if I use `Falcor 4.1`, will I get both `OpenVR` and `real-time path tracing`? Any suggestion about using an old version? I need real-time path tracing on vr, currently trying with OpenXR, but if there is already a working version then I no need to reinvent the wheel
