### ISSUE TITLE
Falcor 4.2 -> 4.3 | HelloDXR Sample Runtime Initialize Error

### ISSUE THREAD

**Issue by kevanvanderstichelen** [NVIDIAGameWorks/Falcor#266]
HelloDXR sample works on version 4.2 after updating it to 4.3 it does not. Other samples such as ModelViewer works perfectly fine, only the Raytracing samples have issues.

**Having this error:** 
pDevice5->CreateStateObject(&objectDesc, IID_PPV_ARGS(&pState->mApiHandle)).
Error! The parameter is incorrect

I have the latest Graphics Driver (457.51) and SDK (10.0.19041.1).

This may be an issue with the fallback cards, I am currently using a GTX 1060TI card. Apparently, on RTX cards this works perfectly.

**Comment by kevanvanderstichelen** [comment]
prerequisites have apparently changed between 4.2 and 4.3. (RTX card was optional before)

**Comment by Y-ZIQI** [comment]
I also have the same error when running FalcorTest. And I found that among the tests in FalcorTest, this error arose when the shaderModel is "6_5"(at function ctx.createProgram()). 
I think my card may not sopport the shaderModel 6.5, my card is GTX 1660 SUPER. In fact, I don't know whether shaderModel matters with hardware or software. Maybe an RTX card works. Now I'm working with Falcor 4.2.
