### ISSUE TITLE
GBufferRaster pass not providing correct results

### ISSUE THREAD

**Issue by VicentChen** [NVIDIAGameWorks/Falcor#268]
Hello,

I'm using Falcor 4.3. I tried to denoise path tracing result with SVGF but failed to generate the "PositionNormalFwidth" with `GBufferRT`. Therefore I ray traced the scene "ZeroDay/MEASURE_ONE.fbx" with `GBufferRaster` pass.

Here is the result. There supposed to be a white rectangular inside red region.
![render_output](https://user-images.githubusercontent.com/17453566/105670917-d1e37580-5f1c-11eb-8654-7a16f3b36804.png)

I debugged with nsight and found that gbuffers provided by `GBufferRaster` have similar artifacts:
![gbuffer](https://user-images.githubusercontent.com/17453566/105671574-e6743d80-5f1d-11eb-9d8a-718815dbf974.png)

Also I rendered the scene with `ForwardRenderer.py` and got similar artifacts. But if I render the same scene with `GBufferRT` everything works fine.

By the way, is there any way to generate the "PositionNormalFwidth" buffer with `GBufferRT`?

Thank you in advance!

**Comment by VicentChen** [comment]
It's my fault.
It's a z-fighting issue. I adjust the near plane to 0.1 and every thing works fine.
Sorry to be a bother.

**Comment by bipul-mohanto** [comment]
Hi @VicentChen, did you use  nsight graphics for debugging?

**Comment by VicentChen** [comment]
> Hi @VicentChen, did you use nsight graphics for debugging?

Yes
