### ISSUE TITLE
"sd.metallic" does not affect apperance at all

### ISSUE THREAD

**Issue by DQLin** [NVIDIAGameWorks/Falcor#271]
What is "sd.metallic" doing? In "BxDF.slang", it only changes the sampling probability. The "eval" function does not evaluate diffuse BRDF if metallic == 1. So using a metallic value between 0 and 1 does not change apperance at all.

**Comment by skallweitNV** [comment]
`sd.metallic` was removed with the new material system. The metallic parameter is used in `StandardMaterial.slang` to compute the diffuse and specular colors. It's still passed to `BxDF.slang` but only for the sampling weights.
