### ISSUE TITLE
UI disallows loading .hdr environment maps

### ISSUE THREAD

**Issue by pierremoreau** [NVIDIAGameWorks/Falcor#276]
When pressing the "Load" button under "EnvMap", hdr files are not listed in the filters and therefore can not be selected for loading. hdr files are supported by Falcor for environment maps, as the different scenes in ORCA (such as the different Bistro ones) come with such a file that loads just fine from the scene script.

Looking at the code, it comes from `Bitmap::getFileDialogFilters()` being called with `ResourceFormat::RGBA32Float` as argument (which is neede to get .exr and .pfm to show up in the filters). The code only allows .hdr in the list of filters, if `ResourceFormat::Unknown` was passed instead.

**Comment by skallweitNV** [comment]
This should be fixed with the 4.4 release.

**Comment by pierremoreau** [comment]
Indeed, thank you!
