### ISSUE TITLE
5.0-preview fails because of pybind11

### ISSUE THREAD

**Issue by gonsolo** [NVIDIAGameWorks/Falcor#290]
The build fails with "pybind11" not found.
I did the following things:
1. Manually download pybind11 and put pybind11/include/pybind into externals folder
2. Change includes from <> to "" in ScriptingBindings.h
Then it builds but crashes:
(Error) ImportError: generic_type: type "bool2" is already registered!
and
(Error) Can't start the python interpreter. Exception says ImportError: Object of type 'module' is not an instance of 'generic_type'

I have vcpkg installed but still consider it a Falcor bug if it just doesn't work.
pybind11 seems to not to be downloaded from packman.

I'm happy to help make the default experience more smooth if someone is interested.

**Comment by skallweitNV** [comment]
There should no need for downloading pybind11. Packman should download all the dependencies (minus the SDK's that need to be downloaded manually due to the license). So I'm a bit puzzled why this didn't work for you.

**Comment by gonsolo** [comment]
There is no directory "pybind11" anywhere.

Source/Externals looks like this:
dds_header/  dear_imgui_addons/  hypothesis/  lz4_stream/  xoshiro/

Source/External/.packman looks like this:
WinPixEventRuntime@  agility-sdk@  dear_imgui@  deps@  dxcompiler@  nanovdb@  nv-usd-debug@  nv-usd-release@  nvtt@  python@  slang@

I inferred that pybind11 would be downloaded in one of those directories.

**Comment by skallweitNV** [comment]
@gonsolo `pybind11` is part of the `falcor_dependencies` package downloaded through packman. You should have it in `Source/External/.packman/deps`. This package contains prebuilt binaries (using vcpkg) for all the OSS libraries we use. Something must have gone wrong during the download of that package. Not sure why `packman` didn't manage to get it. You can manually grab it here: https://d4i3qtqj3r0z5.cloudfront.net/falcor_dependencies@6adad071-windows-x86_64.7z

**Comment by gonsolo** [comment]
Ok.

Source/Externals/.packman/deps/share/pybind11 was there,
Source/Externals/.packman/deps/include/pybind11 was missing.

I manually copied include/pybind11 from the provided package and it seems to work now, thanks.

**Comment by skallweitNV** [comment]
I'm still puzzled this didn't work out of the box. One thing to be aware of: If you change the contents of any of the folders downloaded through `packman`, it won't detect that. So maybe you have changed some of the contents of your local copy of the `falcor_dependencies` package. You could try removing both the `Externals/.packman/deps` link as well as the local packman package in `[packman-repo]/chk/falcor_dependencies` and have packman re-download it. It really should just work then.

**Comment by gonsolo** [comment]
Since it works now I won't touch it. :) If this happens again in the final version I will investigate (and reopen). Thanks.
