### ISSUE TITLE
Starting Mogwai fails with Python error

### ISSUE THREAD

**Issue by oerlich** [NVIDIAGameWorks/Falcor#292]
Falcor Version: 5.0 (current top of tree as of 1/31/2022)

Windows Version: 21H1 (Build 19043.1466)

GPU: RTX 2070 Super

Graphics Driver Version: 471.41

I have completely cleaned other installations of Python from my machine, to make sure there is no interference by anything on my PATH, and made sure I had a completely clean download of the Falcor repo and that the packman-repo directory was all new. I ran the update_dependencies.bat script in Falcor/Tools, then built the solution, which produced no errors. I then set Mogwai as the Startup Project in VS2019, and attempted to start the project, which then produced this python error and stopped execution:

```
Error processing line 1 of C:\Users\Oren\Desktop\Falcor\Bin\x64\Release\Python\lib\site-packages\sphinxcontrib_fulltoc-1.2.0-py3.7-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\Oren\Desktop\Falcor\Bin\x64\Release/Python\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "C:\Users\Oren\Desktop\Falcor\Bin\x64\Release\Python\lib\importlib\__init__.py", line 51, in <module>
      _w_long = _bootstrap_external._w_long
  AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'

Remainder of file ignored
```

I tried looking for other solutions to this issue and they all revolved around conflicting versions of Python being installed and present on the PATH, but like I said I made sure this could not be the case. The only versions of Python Falcor could be running into are the ones it downloaded as part of its dependencies so I am not sure what the issue is here.

**Comment by skallweitNV** [comment]
Do you have `vcpkg` installed and integrated with VS? We're investigating, but there seems some interference when `vcpkg` is installed.

**Comment by skallweitNV** [comment]
I was able to repro this locally. Installing the vcpkg VS integration interferes with the build. Here is what vcpkg documentation says about the integration:

> This will implicitly add Include Directories, Link Directories, and Link Libraries for all packages installed with Vcpkg to all VS2015, VS2017 and VS2019 MSBuild projects. We also add a post-build action for executable projects that will analyze and copy any DLLs you need to the output folder, enabling a seamless F5 experience

So this will inevitably interfere with the build process no matter what. It seems the only solution here is to remove the vcpkg VS integration using `vcpkg integrate remove`. @oerlich can you try that on your end?

**Comment by skallweitNV** [comment]
Closing this.

**Comment by oerlich** [comment]
Sorry for the late update. This did fix the issue. Thanks!
