### ISSUE TITLE
cudaExternalMemoryGetMappedMipmappedArray failed with error invalid argument

### ISSUE THREAD

**Issue by daseyb** [NVIDIAGameWorks/Falcor#293]
Falcor Version: 5.0 (current top of tree as of 2/22/2022)

Windows Version: 21H1 (Build 22000)

GPU: NVIDIA TITAN RTX / NVIDIA GeForce RTX 2080

Graphics Driver Version: 511.23

CUDA version: 11.3

When I run the CudaInterop sample, I get the error `cudaExternalMemoryGetMappedMipmappedArray failed with error invalid argument`, in `FalcorCUDA.cpp` on line 185. I followed the instructions in the README to enable CUDA support and earlier CUDA calls seem to succeed.

Thanks for your help!

**Comment by trsh** [comment]
Its this fixed with latest release?

**Comment by skallweitNV** [comment]
This should work in the latest release. Please reopen if you still have issues.
