### ISSUE TITLE
[Question] How to read texture data from C + + code?

### ISSUE THREAD

**Issue by texwood0935** [NVIDIAGameWorks/Falcor#304]
Hi,
I am a beginner in Falcor framework without prior knowledge in D3D12/11 and HLSL. I want to calculate some data using DXR and I use a textrue to store the data. Now I want to processing the data in C++ code, but I don't know how to read the data which I save in textrue. So I want to know how to read the data in the textrue from C++ code?

**Comment by WeakKnight** [comment]
You need to create a staging texture and then use copy resource command copy your data texture into the staging texture. The staging texture is mappable. You can get a pointer from texture map api.

**Comment by WeakKnight** [comment]
Overall Suggestion For You: 
1. Read The Source Code. Many test cases do this kind of operation.
2. Learn D3D12. It is important for you to have a basic understanding of modern graphics api.

**Comment by texwood0935** [comment]
> Overall Suggestion For You:
> 
> 1. Read The Source Code. Many test cases do this kind of operation.
> 2. Learn D3D12. Falcor is a fast prototyping library for Graphics Developer but it is still important for you to have a basic understanding of modern graphics api.

Thank you for your suggestions. I will learn d3d12 to use Falcor. 
Many test cases provide examples of the functions I need. I will read the source code to know how to use it.

**Comment by WeakKnight** [comment]
> > Overall Suggestion For You:
> > 
> > 1. Read The Source Code. Many test cases do this kind of operation.
> > 2. Learn D3D12. Falcor is a fast prototyping library for Graphics Developer but it is still important for you to have a basic understanding of modern graphics api.
> 
> Thank you for your suggestions. I will learn d3d12 to use Falcor. Many test cases provide examples of the functions I need. I will read the source code to know how to use it.

Check "TextureTests.cpp" maybe helpful for you
