### ISSUE TITLE
Falcor5.1 build error

### ISSUE THREAD

**Issue by Recope** [NVIDIAGameWorks/Falcor#307]
I have tried to build falcor5.1 on both devices, but failed for the following reasons. How can I solve this problem?

Error MSB3073 command "Call G: Falcor Source Falcor.. \.. \Build\prebuild.bat G:\Falcor\Source\Falcor\\.. \ G:\Falcor\ G:\Falcor\Source\Falcor\ x64 x64 DebugD3D12 G:\Falcor\Bin\x64\Debug\
:VCEnd "has exited, code 1. Falcor	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	145

**Comment by trsh** [comment]
@Recope I can confirm that its not a Falcor issue. I am on Windows 10/11 and VS2019 and it builds fine. Did you fallow closely to the instructions in Readme? Read it carefully trough, starting with Prerequisites.

**Comment by Recope** [comment]
> @Recope I can confirm that its not a Falcor issue. I am on Windows 10/11 and VS2019 and it builds fine. Did you fallow closely to the instructions in Readme? Read it carefully trough, starting with Prerequisites.
Version 5.0 built successfully on my device, 5.1 did not, and I'm not sure 5.1 really works.

**Comment by trsh** [comment]
> Version 5.0 built successfully on my device, 5.1 did not, and I'm not sure 5.1 really works.

As I said, it does. Can you provide full error stack and your hardware & OS specs?

**Comment by Recope** [comment]
> > Version 5.0 built successfully on my device, 5.1 did not, and I'm not sure 5.1 really works.
> 
> As I said, it does. Can you provide full error stack and your hardware & OS specs?
**The following is the error:**
Package 'slang' at version '0.23.7' is missing from local storage.
1>Traceback (most recent call last):
1>  File "E:\packman-repo\packman-common\6.42\run.py", line 5, in <module>
1>    packman.main.main_with_exception_handler(sys.argv[1:])
1>  File "E:\packman-repo\packman-common\6.42\packman\main.py", line 2661, in main_with_exception_handler
1>    main(argv)
1>  File "E:\packman-repo\packman-common\6.42\packman\main.py", line 2633, in main
1>    ret = args.func(**vars(args))
1>  File "E:\packman-repo\packman-common\6.42\packman\utils.py", line 506, in wrapper_message_block
1>    return func(*args, **kwargs)
1>  File "E:\packman-repo\packman-common\6.42\packman\main.py", line 1109, in pull_cmd
1>    variable_file,
1>  File "E:\packman-repo\packman-common\6.42\packman\main.py", line 1232, in pull_with_variable_file
1>    args=args,
1>  File "E:\packman-repo\packman-common\6.42\packman\main.py", line 1384, in pull_dependencies
1>    package_name, package_version
1>  File "E:\packman-repo\packman-common\6.42\packman\transport\httptransport.py", line 113, in get_package_path
1>    if self.is_file_found(path):
1>  File "E:\packman-repo\packman-common\6.42\packman\transport\httptransport.py", line 100, in is_file_found
1>    r = self._call_with_retry(lambda: requests.head(protocol_and_path))
1>  File "E:\packman-repo\packman-common\6.42\packman\transport\httptransport.py", line 79, in _call_with_retry
1>    return func()
1>  File "E:\packman-repo\packman-common\6.42\packman\transport\httptransport.py", line 100, in <lambda>
1>    r = self._call_with_retry(lambda: requests.head(protocol_and_path))
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\requests-2.25.1\requests\api.py", line 104, in head
1>    return request('head', url, **kwargs)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\requests-2.25.1\requests\api.py", line 61, in request
1>    return session.request(method=method, url=url, **kwargs)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\requests-2.25.1\requests\sessions.py", line 542, in request
1>    resp = self.send(prep, **send_kwargs)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\requests-2.25.1\requests\sessions.py", line 655, in send
1>    r = adapter.send(request, **kwargs)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\requests-2.25.1\requests\adapters.py", line 449, in send
1>    timeout=timeout
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\urllib3-1.26.6\urllib3\connectionpool.py", line 696, in urlopen
1>    self._prepare_proxy(conn)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\urllib3-1.26.6\urllib3\connectionpool.py", line 964, in _prepare_proxy
1>    conn.connect()
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\urllib3-1.26.6\urllib3\connection.py", line 359, in connect
1>    conn = self._connect_tls_proxy(hostname, conn)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\urllib3-1.26.6\urllib3\connection.py", line 506, in _connect_tls_proxy
1>    ssl_context=ssl_context,
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\urllib3-1.26.6\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
1>    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
1>  File "E:\packman-repo\packman-common\6.42\packman\site-packages\urllib3-1.26.6\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
1>    return ssl_context.wrap_socket(sock)
1>  File "E:\packman-repo\python\3.7.12-windows-x86_64\lib\ssl.py", line 423, in wrap_socket
1>    session=session
1>  File "E:\packman-repo\python\3.7.12-windows-x86_64\lib\ssl.py", line 827, in _create
1>    raise ValueError("check_hostname requires server_hostname")
1>ValueError: check_hostname requires server_hostname
and this is my device specs:
windows10 20H2, RTX3090, NVIDIA driver 512.15, and VS2019.

**Comment by trsh** [comment]
Check your `....\Falcor\Source\Externals\.packman` directory. If its there at all and if inside of it there is a valid `/slang` directory/symlink.

**Comment by Recope** [comment]
> 
sorry, there are no /slang  directory/symlink.

**Comment by Recope** [comment]
> 

sorry, there are no /slang  directory/symlink. Dependencies are not downloaded.

**Comment by trsh** [comment]
Are you behind a Proxy server? 
Also check your Python and PIP versions.

**Comment by Recope** [comment]
> Are you behind a Proxy server? Also check your Python and PIP versions.

Indeed, I am currently in China, so I can only access the Internet through an  proxy server.

**Comment by trsh** [comment]
Try to google on "check_hostname requires server_hostname", there are lots of solutions. Its a Python + Proxy problem.
