### ISSUE TITLE
NameError: Name WindowPaths is not defined when using RenderGraphEditor

### ISSUE THREAD

**Issue by Alegruz** [NVIDIAGameWorks/Falcor#309]
# Issue

I was following the [tutorial](https://github.com/NVIDIAGameWorks/Falcor/blob/master/Docs/Tutorials/03-Creating-and-Editing-Render-Graphs.md).

But every time I try to load an image to the `ImageLoader` by pressing the Load File button, 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/27753696/163763590-599ae582-f58f-4e8a-94ad-099cb6ac446d.png">

Following dialog appears.

# Steps

* Run `RenderGraphEditor`
* Add an `ImageLoader` pass to the graph
* Press Load File button

or

* Run `RenderGraphEditor`
* Add an `ImageLoader` pass
* Open in Mogwai without loading any image

<img width="327" alt="image" src="https://user-images.githubusercontent.com/27753696/163763820-e312585e-954d-4a99-bccc-ff1ce33c6ad8.png">

* Run `RenderGraphEditor`
* Add an `ImageLoader` pass
* Save the graph
* Load the saved graph

![image](https://user-images.githubusercontent.com/27753696/163763954-c888e488-e432-422f-8767-c2e8cc02d7b8.png)

**Comment by tomandjake** [comment]
+1

**Comment by tomandjake** [comment]
Problem in reflection and UI. Script is fine.

**Comment by Shardenn** [comment]
+1
@tomandjake , any easy fix known?

**Comment by eisen** [comment]
In case anyone else (like me) runs into this issue, this is how I fixed it:

In Source/Falcor/Utils/Scripting/Scripting.cpp, change line 60 to:
`Scripting::runScript("from falcor import *\nfrom pathlib import WindowsPath");`

In Source/RenderPasses/ImageLoader/ImageLoader.cpp, change line 87 to:
`if (!mImagePath.empty() && mImagePath.compare(".") != 0)`

**Comment by augustvc** [comment]
+1
Because you misspelled WindowsPath I couldn't find this with google. So here goes: NameError: name 'WindowsPath' is not defined
Thanks eisen for the fix :)
