### ISSUE TITLE
How is Falcor able to load 3 billion triangles scene?

### ISSUE THREAD

**Issue by Recope** [NVIDIAGameWorks/Falcor#314]
I saw this exciting result at GDC 2022:
https://research.nvidia.com/publication/2022-03_research-advances-toward-real-time-path-tracing
But when I loaded the scene of 300 million triangles, Falcor informed me that I had exceeded the capacity of the Vertex buffer：
![image](https://user-images.githubusercontent.com/41226982/172340516-4fe20236-16aa-4346-af85-cd16ed5399f4.png)

**Comment by Recope** [comment]
Is there a problem with the way my scene loads? :(

**Comment by skallweitNV** [comment]
There is currently a limitation to the number of _unique_ triangles as we don't split geometry into multiple buffers. Most of our demo scenes use a fair amount of _instanced_ geometry, so you can get way more _instanced_ triangles than there is space for _unique_ triangles_. This limitation is currently being refactored but it will take some time to land.
