### ISSUE TITLE
HOW to build falcor?

### ISSUE THREAD

**Issue by Derry-Xing** [NVIDIAGameWorks/Falcor#315]

**Comment by 20481535** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'Falcor\Bin\x64\Release\Falcor.lib'

**Comment by 20481535** [comment]
Issues on building falcor

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	Unsupported geometry output type in convertCurveGeomData	Falcor	E:\OTHERS_WORKS\falcor\Falcor\Source\Falcor\Scene\Importers\USDImporter\ImporterContext.cpp	691

**Comment by skallweitNV** [comment]
We just release Falcor 5.2 which switched to CMake. Maybe you could retry following the README and report any problems you run into? Make sure to run a recent version of VS2019/VS2022
