### ISSUE TITLE
gitlab-master.nvidia.com

### ISSUE THREAD

**Issue by PauloMarangoni** [NVIDIAGameWorks/Falcor#319]
Hi,

When I try to run the bat file, cmake can't find the url below:
https://gitlab-master.nvidia.com/tmueller/tiny-cuda-nn.git 

I switched to https://github.com/NVlabs/tiny-cuda-nn in the .gitmodules and it seems to be working.

**Comment by PauloMarangoni** [comment]
nlohmann/json.hpp and pybind11_json.hpp seems to be missing too, I added manually and the project is building

**Comment by trsh** [comment]
@PauloMarangoni I replaced  https://github.com/NVlabs/tiny-cuda-nn in .gitmodules, still it tries to access https://gitlab-master.nvidia.com/tmueller/tiny-cuda-nn.git . How, why?

**Comment by trsh** [comment]
Uff, after some manual work this now:

```
-- Updating packman dependencies ...
CMake Error at CMakeLists.txt:103 (include):
  include could not find requested file:

    mt-retry
```

**Comment by ksang** [comment]
Had same issue, added submodules by running:

git submodule add https://github.com/nlohmann/json.git external/json
git submodule add https://github.com/pybind/pybind11_json.git external/pybind11_json

And then copy missing header files to corresponding external/include location should fix the issue.

**Comment by Raymark97** [comment]
> @PauloMarangoni I replaced https://github.com/NVlabs/tiny-cuda-nn in .gitmodules, still it tries to access https://gitlab-master.nvidia.com/tmueller/tiny-cuda-nn.git . How, why?
> 
> Update:
> 
> I did `git submodule sync`
> 
> And the this
> 
> ```
> fatal: remote error: upload-pack: not our ref 488d1e51352d01547426008e6b6eae5d52ba5b3d
> fatal: Fetched in submodule path 'external/tiny-cuda-nn', but it did not contain 488d1e51352d01547426008e6b6eae5d52ba5b3d. Direct fetching of that commit failed.
> ```
> 
> So I just copied the package tiny-cuda-nn contents manually inside :/

any ideas on how to fix this? i'm having the same issue

**Comment by trsh** [comment]
@Raymark97 the solution is in my last sentence.

**Comment by Raymark97** [comment]
> @Raymark97 the solution is in my last sentence.

so you just added manually the tiny-cuda repo and removed `#include(mt-retry)`?

**Comment by trsh** [comment]
Well that all what I did:
1. I switched to https://github.com/NVlabs/tiny-cuda-nn in the .gitmodules.
2. Run `git submodule sync`
3. Commented out `include(mt-retry)` so its not used (don't remember the file).
4. The then process run with reporting errors about `not our ref` about tiny cuda, but completed.
5. Then I copied `tiny-cuda-nn` contents manually by downloading a zip from repo (the folder was present in /external).

It might be ok if you don't get `include(mt-retry)` error. I think its some Windows thingy. I am on win 11 btw

**Comment by Raymark97** [comment]
> @Raymark97 Well this is all I did:
> 
> 1. I switched to https://github.com/NVlabs/tiny-cuda-nn in the .gitmodules.
> 2. Run `git submodule sync`
> 3. Commented out `include(mt-retry)` so its not used (don't remember the file).
> 4. The process run with reporting errors about `not our ref` about tiny cuda, but completed.
> 5. Then I copied `tiny-cuda-nn` contents manually by downloading a zip from repo (the folder was present in /external).
> 
> It might be ok if you don't get `include(mt-retry)` error. I think its some Windows thingy. I am on win 11 btw

so without re-running the setup at the end?

**Comment by pure-water** [comment]
I did 1 myself . Skipping 2,3,4 and it can  complete the compile. But cuda_nn is empty anyway. So I just mannually pu the tiny-cuda-nn into external directory?

**Comment by trsh** [comment]
Yes

**Comment by msgfx** [comment]
I have resolved this issue in the following way.
My work branch is https://github.com/msgfx/Falcor/commit/77970a1069ffebbf44697e16e87a33bcb3f8ef30
On Windows, About step 4 and 5, user would remove manually on windows explorer.
1. cd external
2. git submodule deinit -f tiny-cuda-nn
3. git rm -f tiny-cuda-nn
4. cd ../
5. rm -rf .git/modules/external/tiny-cuda-nn
6. cd external
7. git submodule add https://github.com/NVlabs/tiny-cuda-nn.git
8. cd ../
9. setup_vs2022.bat

Note:
tiny-cuda-nn repository have json and pybind11_json.

My environments:
Windows 11 Pro, 21H2

**Comment by trsh** [comment]
Not sure why nvidia has this issue tracker open. Nobody really cares :)

**Comment by PauloMarangoni** [comment]
@trsh you are right, nobody cares. it's been almost 2 months since I open this issue and nothing was change.
seeing the number of comments here, no one can run this project without manually fixing the problem.

**Comment by skallweitNV** [comment]
Sorry for not responding to this earlier. We're a small team supporting Falcor and unfortunately the public version does not get enough attention most of the time. I've pushed a fix for this now.
