### ISSUE TITLE
Issues while building on 2022 VS

### ISSUE THREAD

**Issue by trsh** [NVIDIAGameWorks/Falcor#320]
![2022-08-18_092030](https://user-images.githubusercontent.com/3727523/185308358-e1b0bd81-6c30-485b-9dbe-10194b2031b4.png)

**Comment by trsh** [comment]
Incompatibility with SDK 7.5 , 7.4 works.

**Comment by skallweitNV** [comment]
Yes, the README states that it's tested with Optix 7.3 actually. We will consider updating to the newest version.
