### ISSUE TITLE
SDF renderings looks bugous and bad

### ISSUE THREAD

**Issue by trsh** [NVIDIAGameWorks/Falcor#321]
![2022-08-18_100021](https://user-images.githubusercontent.com/3727523/185325515-4af0ea5b-c7de-413c-a2a0-850cc1159a29.png)

**Comment by trsh** [comment]
Hello Nvidia guys. Any fallow up on this? @skallweitNV ?

**Comment by skallweitNV** [comment]
Looks like the latest preview release shows the same issue. We currently don't have people working on this feature, so it will probably not be fixed for the time being.
