### ISSUE TITLE
RTXGI crash when saving the RenderGraph

### ISSUE THREAD

**Issue by pantelis-kan** [NVIDIAGameWorks/Falcor#322]
When opening the Graph Editor, if I insert a RTXGI  pass and try to save to a .py file, then the Editor simply crashes and closes without any error. As far as I know this only happens if I insert the RTXGI pass. All the other passes seem to work fine when I try to save them.

**Comment by skallweitNV** [comment]
RTXGI is no longer supported and removed along with most of the raster passes.
