### ISSUE TITLE
issues on getting tiny-cuda

### ISSUE THREAD

**Issue by pure-water** [NVIDIAGameWorks/Falcor#323]
I have issues on setting falcor up on tiny cuda NN. I have the following error by changing the gitlab to github tiny_cuda_nn

![image](https://user-images.githubusercontent.com/2059536/193439957-21dc08a4-fece-4e71-960c-105309fe0488.png)

It seems ok apart from this. 

What is the best way forward? 

Regards
Yao

**Comment by trsh** [comment]
Dupe ? https://github.com/NVIDIAGameWorks/Falcor/issues/319

**Comment by skallweitNV** [comment]
Should be fixed now.
