### ISSUE TITLE
Out-of-date tutorial

### ISSUE THREAD

**Issue by Mirage-c** [NVIDIAGameWorks/Falcor#335]
Falcor\docs\tutorials\04-writing-shaders.md seems to be out-of-date.
As an example, in WireframePass::execute(), Scene::RenderFlags doesn't even seem to be a valid class now.
Could you please update the tutorial file, or am I somewhere wrong?

**Comment by udemegane** [comment]
Yes, tutorials are outdated. I create a pull request: https://github.com/NVIDIAGameWorks/Falcor/pull/336

**Comment by bipul-mohanto** [comment]
@udemegane, thanks for noticing. I guess, besides the tutorial, the [Falcor home](https://developer.nvidia.com/falcor) is also outdated as it says Falcor supports `Stereo rendering using OpenVR `. I did not see openvr in Falcor 7.0.
