### ISSUE TITLE
How to load/render the images on the Github site?

### ISSUE THREAD

**Issue by lonnietc** [NVIDIAGameWorks/Falcor#337]
Hello,

I just found Falcor and have been able to compile it successfully.

Now I would like to render the images in your teaser.jpg

![image](https://user-images.githubusercontent.com/15264930/216779865-71105111-73c0-43ee-8785-92ac27c0a595.png)

how can this be done?
Thanks

**Comment by lonnietc** [comment]
Hello,

Is there any update on this?

Thanks

**Comment by knightcrawler25** [comment]
1. Download the scene file (pbrt-v4 version) from https://benedikt-bitterli.me/resources/ and unzip it.
2. Open up Mogwai.exe from your build folder
3. File -> Load Scene and select the *.pbrt scene file that you've downloaded
4. File -> Load Script and browse to <SourceFolder>\Falcor\Source\Mogwai\Data\PathTracer.py

**Comment by lonnietc** [comment]
Thanks @knightcrawler25 that worked out just right for me.
