### ISSUE TITLE
Crashes when loading scene

### ISSUE THREAD

**Issue by ttnghia** [NVIDIAGameWorks/Falcor#34]
Problem: I ran the FeatureDemo app and it crashed when loading a scene file (I tested on 3/4 scenes from here: https://developer.nvidia.com/orca). Note that the app only crashes if it was built in release mode.

I debug the app in visual studio and fotunately MSVC catches an exception at line 95, file Framework\Source\Utils\Platform\Window\ProgressBarWin.cpp, which is:

```
SetWindowTextA(pData->hwnd, msgList[pData->dist(pData->rng)].c_str()); 
```

I commented this line out and the app works. Apparently there is a bug at this line.

**Comment by nbenty** [comment]
Hi Nghia,
Thanks for reporting it. Unfortunately I can't reproduce it.
Can you let me know which version of the OS and SDK version you are using?

Thanks!

**Comment by ttnghia** [comment]
Hi,
I'm using Windows 10, VS2017 and Windows SDK 10.0.16299.0.
I look at the code again, line 95:
``
SetWindowTextA(pData->hwnd, msgList[pData->dist(pData->rng)].c_str());
``

If I change it to `SetWindowTextA(pData->hwnd, msgList[0].c_str());` then I don't have crash. I guess that the random generator object _pData->dist_ has not been initialized properly.

**Comment by ttnghia** [comment]
I just debug my program more carefully in release build, changing the line above to:
``
auto x = pData->dist(pData->rng);
SetWindowTextA(pData->hwnd, msgList[x].c_str());
``
When the program break due to access violation exception, MSVC shows that the values for `x` is 1, despite that `pData->dist` has been initialized with min/max = 0, 0. I suspect that the problem is due to a bug in the compiler such that the uniform_int_distribution object generates of of range value when its min/max are all 0.

**Comment by nbenty** [comment]
That's strange.
I'll go over the documentation to make sure I'm not using it incorrectly. Worst case I'll clamp the result myself.
Thanks!

**Comment by nbenty** [comment]
This doesn't appear to happen anymore
