### ISSUE TITLE
Troubles with 6.0-preview (Falcor python won't build in Debug build) 

### ISSUE THREAD

**Issue by trsh** [NVIDIAGameWorks/Falcor#340]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
call ..\..\bin\Debug\setpath.bat & C:/Projects/Falcor/external/packman/python/python.exe C:/Projects/Falcor/build_scripts/generate_stubs.py C:/Projects/Falcor/build/windows-vs2022/bin/Debug/python
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	FalcorPython	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	159	
```

**Comment by tomas-davidovic** [comment]
Can you please provide more information on repro steps?
I've done a fresh clone, ran `setup_vs2022.bat`, opened the `build\windows-vs2022\Falcor.sln` in a freshly installed Visual Studio 2022, switched to Debug and x64, pressed F7 to Build Solution (Build -> Build Solution) and it all built just fine.

**Comment by trsh** [comment]
> Can you please provide more information on repro steps? I've done a fresh clone, ran `setup_vs2022.bat`, opened the `build\windows-vs2022\Falcor.sln` in a freshly installed Visual Studio 2022, switched to Debug and x64, pressed F7 to Build Solution (Build -> Build Solution) and it all built just fine.

I did exactly the same

**Comment by tomas-davidovic** [comment]
Can you go into (probably) `c:\packman-repo`, just flat out delete it as well as the cloned directory and try again? I've been trying to reproduce on our side since morning and have absolutely no luck, so I'd try to get to as clean slate as possible.

**Comment by trsh** [comment]
> Can you go into (probably) `c:\packman-repo`, just flat out delete it as well as the cloned directory and try again? I've been trying to reproduce on our side since morning and have absolutely no luck, so I'd try to get to as clean slate as possible.

Yeah. Can try that at some point.

**Comment by Destiny-Xing** [comment]
> Can you go into (probably) `c:\packman-repo`, just flat out delete it as well as the cloned directory and try again? I've been trying to reproduce on our side since morning and have absolutely no luck, so I'd try to get to as clean slate as possible.

I tried to deal with it this way, but it has no effect. It is consistent with the previous error report.

**Comment by skallweitNV** [comment]
The issue here is related to #341. Answer in other ticket.
