### ISSUE TITLE
unable to fetch tiny-cuda-nn submodule for v5.2

### ISSUE THREAD

**Issue by Pommpy** [NVIDIAGameWorks/Falcor#348]
`fatal: unable to access 'https://gitlab-master.nvidia.com/tmueller/tiny-cuda-nn.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitlab-master.nvidia.com:443`

the url no longer works, what should I do?

**Comment by Pommpy** [comment]
I'd also like to know how to use forward-rendering pipeline in v6.0?

**Comment by Pommpy** [comment]
Fixed. I didn't see the another branch.

**Comment by yillis** [comment]
> I'd also like to know how to use forward-rendering pipeline in v6.0?

Have you solved this problem?
