### ISSUE TITLE
Can Falcor support Python API like mitsuba3?

### ISSUE THREAD

**Issue by GensokyoLover** [NVIDIAGameWorks/Falcor#350]
Both mitsuba and falcor are excellent projects! I have tried to find the information about that in documents in preview 6.0 version.

**Comment by skallweitNV** [comment]
Improved Python support is one of the main focus points on the current internal development. There is some preliminary support in the final 6.0 version, but we are adding much more.

**Comment by swordigo1995** [comment]
@skallweitNV  When will the final 6.0 version be released? Can't wait to use it :)

**Comment by skallweitNV** [comment]
We are working on improved python bindings. It's all very much work in progress though.
