### ISSUE TITLE
How to use multisampleTexture ?

### ISSUE THREAD

**Issue by enemy456** [NVIDIAGameWorks/Falcor#355]
Texture::SharedPtr mpMs = Texture::create2DMS(
        mpDevice.get(), (uint32_t)512, (uint32_t)512, ResourceFormat::RGBA32Float, (uint32_t)8, 1,
       Resource::BindFlags::UnorderedAccess
    );
when I use this code to init MStexture，get error.
I try to use samplecount 2 to 8, also get same error

(Fatal) Assertion failed: mGfxTextureResource
G:\Falcor\Source\Falcor\Core\API\Texture.cpp:677

Stacktrace:
 0# 0x69207974696c6175 ( ?? )
 1# 0x000000002e302073 ( ?? )

But When I change sample count to 1, this code will work.

**Comment by swordigo1995** [comment]
Hi, I also encountered this problem when I wanted to add MSAA to Falcor. Any ideas? @skallweitNV

**Comment by enemy456** [comment]
@skallweitNV

**Comment by swordigo1995** [comment]
@skallweitNV Thanks for your reply! After setting the flag I still failed to build the multi-sampling texture.. Could you please give a multi-sampling example? Many thanks!

**Comment by skallweitNV** [comment]
Since the last update there is a multisampling sample app with example code -> https://github.com/NVIDIAGameWorks/Falcor/blob/master/Source/Samples/MultiSampling/MultiSampling.cpp#L70

**Comment by enemy456** [comment]
Error when validating FBO. Different sample counts in attachments. When i use msaa,it happened
