### ISSUE TITLE
Missing stencil formats

### ISSUE THREAD

**Issue by kopaka1822** [NVIDIAGameWorks/Falcor#356]
I noticed that both stencil formats (D24_S8 and D32_S8) are missing in the latest preview. I saw some comments about D24_S8 only being supported by NVIDIA cards, however, no mentions of the D32_S8.

Will there be support for stencil formats again in the future? I need them in my research since they are more efficient at masking out pixels than supplying a mask and calling discard in the shader (At least the last time I did benchmarks).

**Comment by skallweitNV** [comment]
`D32_S8` will be available in the 6.0 release.
