### ISSUE TITLE
Linking issue with USDImporter when building falcor

### ISSUE THREAD

**Issue by Yishun99** [NVIDIAGameWorks/Falcor#359]
I've been using the Falcor5.0 and Falcor5.2 for a long time and would like to upgrade it to [Falcor6.0-preview2](https://github.com/NVIDIAGameWorks/Falcor/releases/tag/6.0-preview2).

However, I encountered the exactly same issue as reported in [NVIDIA Forum](https://forums.developer.nvidia.com/t/linking-issue-with-usdimporter-when-building-falcor/254867).

Maybe there are some small issues in the latest version of Falcor or in the compatibility between Falcor and nv-usd.

**Comment by Yishun99** [comment]
Hi @skallweitNV , 
I think it's a small but common issue. 
Could you please give me some advices before the stable Falcor6.0? Thanks.

**Comment by skallweitNV** [comment]
It doesn't work with the latest code in `master`? That code successfully ran through CI, so I'm a bit puzzled.
