### ISSUE TITLE
pbrt scene loading error: out of bounds indices

### ISSUE THREAD

**Issue by SirKero** [NVIDIAGameWorks/Falcor#360]
I noticed a loading error with some pbrt scenes because some indices are out of bounds.

The error seems to come from plymeshes, where assimp loads in meshes with faces with 0 indices. 
This happens, for example, with "The Wooden Staircase" scene from Bitterli's rendering resources, where "Mesh230.ply" has a face with 0 indices, which causes random data to be stored in the pIndices array of the mesh.

I lazily fixed this by ignoring the meshes with faces with 0 indices. For that, I added a simple check to the `TriangleMesh::createFromFile()` function from the `Falcor/Scene/TriangleMesh.cpp`:
```
262    const auto& face = mesh->mFaces[faceIdx]; 
+      if (face.mNumIndices != 3u){
+                  logWarning("The mesh from '{}' has a broken face, ignored", fullPath);
+                  return nullptr;
+      } 
263    for (size_t i = 0; i < 3; ++i) indices.emplace_back((uint32_t)(indexBase + face.mIndices[i]));
```

**Comment by skallweitNV** [comment]
Thanks, will fix.
