### ISSUE TITLE
DirectML

### ISSUE THREAD

**Issue by kopaka1822** [NVIDIAGameWorks/Falcor#362]
I was wondering if there are any plans to support the DirectML API in the near future, since machine learning is becoming more popular.

I was hoping that, perhaps you already have some private branches where someone attempted an implementation?

**Comment by skallweitNV** [comment]
No, there are no plans to support the DirectML API.
We are working on other technologies/tools for machine learning.

**Comment by kopaka1822** [comment]
@skallweitNV Hi, can you let me know what technologies/tools you are working with for machine learning?
I was looking for something that allows directX textures as inputs and does the inference on GPU.
