### ISSUE TITLE
Q: Linux status?

### ISSUE THREAD

**Issue by ib00** [NVIDIAGameWorks/Falcor#368]
What is the current status of Falcor on Linux (and Vulkan)?

**Comment by skallweitNV** [comment]
It's in "experimental" status. It should compile and run. We've seen some performance issues with some render passes, but most things should actually work. We don't use it in full "production" yet.

**Comment by L-Aidan** [comment]
Hi, I try to build Falcor in Ubuntu20.04, but failed. I met error like this:
`/home/momei/Desktop/Project/Falcor/external/packman/deps/debug/lib/libopenvdb.so.9.0: undefined reference to pthread_once@GLIBC_2.34'`
Could you tell me which version of Linux that have been tested does work?
Thanks!

**Comment by skallweitNV** [comment]
We use Ubuntu 22.04 LTS for testing.

**Comment by L-Aidan** [comment]
Thanks!
