### ISSUE TITLE
 No module named 'falcor.falcor_ext'

### ISSUE THREAD

**Issue by Lumengine** [NVIDIAGameWorks/Falcor#370]
On release 6.0, building is ok, but when launching either mogwai or render graph editor, No module named falcor.falcor_ext, do I need to add a specific path to PYTHON_PATH ?
Thank you

**Comment by Lumengine** [comment]
Yes, compiling and launching from Visual Studio 2022. And I don't want to use it as a python module.

**Comment by skallweitNV** [comment]
Did you use `Build Solution`? Maybe that helps.

**Comment by Lumengine** [comment]
I did indeed. I'm not in front of my computer right now, I'll do further
test maybe next week. Do you have the path to include ?

Le jeu. 6 juil. 2023, 17:49, skallweitNV ***@***.***> a
écrit :

**Comment by skallweitNV** [comment]
I just tried in Visual Studio 2022 and everything works fine for me. Not sure what the problem is. Did you do a fresh clone or update an existing one? Maybe try a full clone/build.

**Comment by Lumengine** [comment]
I indeed used an old one, + checkout 6.0.
I'll try to reclone and rebuild ! I let you know if it works.
Thanks.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lumengine** [comment]
Sorry for the late answer, I was off. I cloned again and rebuilt and everything is working now ! Thank you !
