### ISSUE TITLE
Falcor 6.0 shader compilation error

### ISSUE THREAD

**Issue by hchoi405** [NVIDIAGameWorks/Falcor#374]
Hello,

First of all, thank you for your efforts on this project.

I'm currently trying to execute Falcor 6.0 on the Linux platform, specifically on Ubuntu 22.04.

I have successfully built the project and launched Mogwai. However, when attempting to load a scene for rendering, I encountered a slang compilation error:

```
(Error) GFX Error: glslang: /Falcor6/Source/Falcor/Scene/RaytracingInline.slang(250): error: '=': ray queries can only be initialized by using the rayQueryInitializeEXT intrinsic: _S607
glslang: /Falcor6/Source/Falcor/Scene/RaytracingInline.slang(250): error: '' : compilation terminated
glslang: note: ERROR: 2 compilation errors. No code generated.
```
Unfortunately, resolving this issue has been challenging, and I haven't found a solution on my own.

Here are the details of my environment:

OS: Ubuntu 22.04
GPU: RTX 4090
Driver: 535.54.03
Configure preset: Linux/GCC

I have also made a modification by commenting out `FALCOR_EXPORT_D3D12_AGILITY_SDK` from Mogwai.cpp. As far as I know, it's not possible to utilize the Agility SDK in Linux.

If you have any insights or suggestions on how to solve this compilation error, I would greatly appreciate your help. Thank you in advance.

**Comment by VicRanger** [comment]
I have encountered the same issue.

env: 
OS: Windows 10 21H2
GPU: RTX3090
Driver: 531.79
Configure preset: Windows - Ninja/MSVC

I am also in search of a solution.

**Comment by skallweitNV** [comment]
slang has changed a lot in the past months so things might have got broken. We have internal CI testing some of the Linux build but the test coverage is far from complete. I will have a look this week.
