### ISSUE TITLE
Falcor 6.0 Vulkan Backend Option

### ISSUE THREAD

**Issue by ayclove** [NVIDIAGameWorks/Falcor#375]
OS : Windows 10
GPU: RTX 3090 Ti
Driver: 536.40
Configure preset: windows-vs2022

---
When I changed the default backend renderer from D3D12 to Vulkan like the below,
I figured that some scripts do not work, for example RTXDI and PathTracer, although MinimalPathTracer works.
I attach the log below, would you please provide me a proper solution to solve this?

---

(Info) Falcor 6.0 (commit: 9fdfdbb3, branch: master, contains uncommitted changes)
(Info) Created GPU device 'NVIDIA GeForce RTX 3090 Ti' using 'Vulkan' API.
(Info) Loaded 29 plugin(s) in 0.301s
...
Rendering/Materials/StandardMaterial.slang() RenderPasses/PathTracer/TracePass.rt.slang(rayGen, scatterMiss, scatterTriangleClosestHitStandard, scatterTriangleAnyHitStandard)
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(171): warning 41016: returning without initializing out parameter 'weight'
            if (min(abs(wi.z), abs(wo.z)) < kMinCosTheta || pdf == 0.f) return false;
                                                                        ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(175): warning 41016: returning without initializing out parameter 'weight'
            if (min(wi.z, wo.z) < kMinCosTheta || pdf == 0.f) return false;
                                                              ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(171): warning 41016: returning without initializing out parameter 'lobeType'
            if (min(abs(wi.z), abs(wo.z)) < kMinCosTheta || pdf == 0.f) return false;
                                                                        ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(175): warning 41016: returning without initializing out parameter 'lobeType'
            if (min(wi.z, wo.z) < kMinCosTheta || pdf == 0.f) return false;
                                                              ^~~~~~

(Warning) Warnings in program:
Rendering/Materials/StandardMaterial.slang() RenderPasses/PathTracer/GeneratePaths.cs.slang(main)
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(171): warning 41016: returning without initializing out parameter 'weight'
            if (min(abs(wi.z), abs(wo.z)) < kMinCosTheta || pdf == 0.f) return false;
                                                                        ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(175): warning 41016: returning without initializing out parameter 'weight'
            if (min(wi.z, wo.z) < kMinCosTheta || pdf == 0.f) return false;
                                                              ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(171): warning 41016: returning without initializing out parameter 'lobeType'
            if (min(abs(wi.z), abs(wo.z)) < kMinCosTheta || pdf == 0.f) return false;
                                                                        ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(175): warning 41016: returning without initializing out parameter 'lobeType'
            if (min(wi.z, wo.z) < kMinCosTheta || pdf == 0.f) return false;
                                                              ^~~~~~

(Warning) Warnings in program:
Rendering/Materials/StandardMaterial.slang() RenderPasses/PathTracer/ReflectTypes.cs.slang(main)
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(171): warning 41016: returning without initializing out parameter 'weight'
            if (min(abs(wi.z), abs(wo.z)) < kMinCosTheta || pdf == 0.f) return false;
                                                                        ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(175): warning 41016: returning without initializing out parameter 'weight'
            if (min(wi.z, wo.z) < kMinCosTheta || pdf == 0.f) return false;
                                                              ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(171): warning 41016: returning without initializing out parameter 'lobeType'
            if (min(abs(wi.z), abs(wo.z)) < kMinCosTheta || pdf == 0.f) return false;
                                                                        ^~~~~~
D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Rendering/Materials/StandardMaterialInstance.slang(175): warning 41016: returning without initializing out parameter 'lobeType'
            if (min(wi.z, wo.z) < kMinCosTheta || pdf == 0.f) return false;
                                                              ^~~~~~

(Error) GFX Error: glslang:  D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Scene/RaytracingInline.slang(250): error :  '=' : ray queries can only be initialized by using the rayQueryInitializeEXT intrinsic: _S607
glslang:  D:/research/RT/Falcor_yc/Falcor/Source/Falcor/Scene/RaytracingInline.slang(250): error :  '' : compilation terminated
glslang: note : ERROR: 2 compilation errors.  No code generated.

**Comment by skallweitNV** [comment]
It looks like recent versions of slang have broken support for ray queries with Vulkan. We will try to fix this.

**Comment by ayclove** [comment]
Thank you in advance :)
