### ISSUE TITLE
Error regarding openvdb

### ISSUE THREAD

**Issue by bipul-mohanto** [NVIDIAGameWorks/Falcor#382]
Hi! 
I am on windows 10, with the latest graphics card and driver. I have just started working on Falcor. I did:
1. `git clone --recursive https://github.com/NVIDIAGameWorks/Falcor.git`
2. run command prompt: `cmake --preset windows-vs2022`
3. manually added the missing libraries, so my configuration looks all good
```
pybind11 v2.9.2
-- Vulkan-Headers = 1.3.238
-- Feature flags:
-- FALCOR_HAS_D3D12: TRUE
-- FALCOR_HAS_VULKAN: ON
-- FALCOR_HAS_AFTERMATH: ON
-- FALCOR_HAS_NVAPI: ON
-- FALCOR_HAS_PIX: ON
-- FALCOR_HAS_CUDA: ON
-- FALCOR_HAS_OPTIX: ON
-- FALCOR_HAS_D3D12_AGILITY_SDK: ON
-- FALCOR_HAS_NRD: ON
-- FALCOR_HAS_DLSS: ON
-- FALCOR_HAS_NV_USD: ON
-- FALCOR_HAS_MDL_SDK: ON
-- FALCOR_ENABLE_USD: ON
```
4. then opened `build/windows-vs2022/Falcor` and `Build Solution`, that is a success.
5. Now, I want to run a sample example. When I am running `Samples/HelloDXR`, it gives me the following error: 

<img width="409" alt="dd" src="https://github.com/NVIDIAGameWorks/Falcor/assets/12484581/6c5c16d7-f3e5-4272-aa48-566042d33d71">

I checked `openvdb` is already in `Falcor\external\packman\deps` directory. I would really appreciate if you could give some suggestion, or what I was doing wrong. Thanks!

**Comment by skallweitNV** [comment]
Can you try either running `setup.bat` before generating the VS solution or just use `setup_vs2022.bat` instead of doing it manually?

**Comment by bipul-mohanto** [comment]
Yea, the problem has been solved with `setup_vs2022.bat`.

**Comment by bipul-mohanto** [comment]
Hi! Thanks for the latest Falcor 8.0. Unfortunately, after the new version, I am getting the same error as before. The googled solutions are not working so far. 

<img width="623" alt="aaaaaaa" src="https://github.com/user-attachments/assets/ca3875ac-2785-4b01-8bed-caa850b4996e">
<img width="609" alt="bbbbbbbbbbbbbbbbbbbbb" src="https://github.com/user-attachments/assets/52afaccf-6b2e-4121-a339-bf263a72161c">
<img width="620" alt="ccccccccccccccccccc" src="https://github.com/user-attachments/assets/2fcb2b61-b11d-4414-8b09-5dca98fd756c">

**Comment by bipul-mohanto** [comment]
I have temporarily resolved the errors, maybe because of a mismatch of the `.dll versions`. for future reference, I have replaced the existing `openvdb` with my `vcpkg` build library. However, it leads to two more runtime errors: in release mode, `Imath-3_1.dll` is missing, and in debug mode, tbb12_debug.dll missing. I also regenerated those with `vcpkg`, so far it is working.
