### ISSUE TITLE
Unable to offset the position of the FBX model in pyscene

### ISSUE THREAD

**Issue by xiaoshux** [NVIDIAGameWorks/Falcor#383]
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/58647630/6481c5de-792b-425a-82e7-87610d1f7392)
I try to modify my fbx model position in .pyscene file by this code:

`sceneBuilder.importScene('mosh.fbx', instances=Transform(scaling=0.2, rotationEulerDeg=float3(90, 90, 0), translation=float3(2.043645,2.878248,-1.383858))) `

But Falcor told me that there was no such parameter Instance:
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/58647630/cffbf153-eddd-47e8-a5ee-754291ef235b)

**Comment by skallweitNV** [comment]
`instances` is deprecated and not supported anymore. Actually the Python API description is out-of-date as we are heavily refactoring things. Will clean some of this up for the next release.
