### ISSUE TITLE
How to use a Python script or .pyscene file to modify the bone matrix in real time

### ISSUE THREAD

**Issue by xiaoshux** [NVIDIAGameWorks/Falcor#384]
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/58647630/c7abe0e4-bc5a-44b8-b4bb-3c6566e51750)
I think this may be a way to modify the bone matrix to become a skin animation, but I don't know how to use it.

**Comment by skallweitNV** [comment]
You cannot modify bone matrices in realtime in current Falcor. We are redesigning the scene code and APIs at this time, but it's still some time away from being ready for the public, sorry!
