### ISSUE TITLE
Shader hot reload for non-RenderPass project

### ISSUE THREAD

**Issue by guiqi134** [NVIDIAGameWorks/Falcor#385]
Hi,

I have a project which is not inheritted from RenderPass class, but it is used as a module in PathTracer project (defined as a class member in PathTracer.h and build as a static library). When I press F5 to reload, only the shaders from those render passes added in .py file will be reloaded. 

So, instead of changing the project to a render pass, is there a way to also hot reload shaders from this module project?

**Comment by SirKero** [comment]
Have you added the shaders to the CMakeList.txt of the PathTracer render pass? (Source/RenderPasses/PathTracer) If not, that should probably fix the hot load problem.

**Comment by guiqi134** [comment]
Oh, it works. Thank you so much!
