### ISSUE TITLE
MSAA in 6.0-preview version

### ISSUE THREAD

**Issue by swordigo1995** [NVIDIAGameWorks/Falcor#386]
Hi~ I want to use MSAA in my render pass in Falcor 6.0-preview version. I found the multisampling sample in Falcor 6.0 version is awesome, I also tested MSAA in the GBufferRaster pass of 6.0 version, and it works pretty well. However, when I tried to follow the same approach to implement it in the 6.0-preview (or preview2) version (both by adapting the new multisampling sample and testing MSAA in the GBufferRaster pass), it throws an error from the gfx when `Texture::getSRV()` is called at this line:
https://github.com/NVIDIAGameWorks/Falcor/blob/eb8f6916967aca83d64dd0877aeab8df20bde6ca/Source/Falcor/Core/API/ResourceViews.cpp#L92

Since our development is based on the 6.0-preview version, and it works well except for MSAA, I am hesitant to fully upgrade to the 6.0 version.

So, do you have any ideas on how to address this error in the 6.0-preview version? Was this problem addressed with any related bug fixes during the development from 6.0-preview2 to 6.0, or was it fixed by upgrading SLANG?

Any ideas would be greatly appreciated!
@skallweitNV 

PS:
I tested MSAA in the GBufferRaster pass by modifying the following two lines in `GBufferRaster::reflect` by changing `texture2D(sz.x, sz.y)` to `texture2D(sz.x, sz.y, 8)`:
https://github.com/NVIDIAGameWorks/Falcor/blob/eb8f6916967aca83d64dd0877aeab8df20bde6ca/Source/RenderPasses/GBuffer/GBuffer/GBufferRaster.cpp#L64
https://github.com/NVIDIAGameWorks/Falcor/blob/eb8f6916967aca83d64dd0877aeab8df20bde6ca/Source/RenderPasses/GBuffer/GBuffer/GBufferRaster.cpp#L68

**Comment by swordigo1995** [comment]
@skallweitNV  Any idea? Thanks very much!

**Comment by skallweitNV** [comment]
Hi @swordigo1995, unfortunately I'm not aware of any change that would be relevant here, but I might just have forgotten about it. So you are saying things work correctly in the latest 6.0 release, whereas in the preview releases it didn't work?

**Comment by skallweitNV** [comment]
So there was this fix in slang/gfx: https://github.com/shader-slang/slang/pull/2880

This released with slang 0.27.21 https://github.com/shader-slang/slang/releases/tag/v0.27.21

6.0 uses slang 2023.0.3
6.0-preview2 uses slang 0.27.14
6.0-preview uses slang 0.24.52

So yeah, the preview versions didn't have that bug fixed. So I guess you might be fine by just updating to slang 0.27.21

Hope that helps.

**Comment by swordigo1995** [comment]
Thanks a lot!

**Comment by swordigo1995** [comment]
It works! Thank you.
