### ISSUE TITLE
Fail to build Falcor 6.0 on Windows

### ISSUE THREAD

**Issue by zheng95z** [NVIDIAGameWorks/Falcor#387]
Hi team,

Thank you all for your efforts on pushing Falcor 6.0 to real.

I'm trying to build Falcor 6.0 on the Windows platform.

When I tried to build it using CMake and VS code using `Windows Ninja/MSCV` preset, I first encountered the warning C4819. I fixed it using the trick in [this PR](https://github.com/NVIDIAGameWorks/Falcor/pull/326).

Then I got another error, which seems from the USD importer:
```bash
[build] osdCPU.lib(level.cpp.obj) : error LNK2019: unresolved external symbol __std_find_trivial_4 referenced in function "int * __cdecl std::_Find_unchecked<int *,int>(int *,int * const,int const &)" (??$_Find_unchecked@PEAHH@std@@YAPEAHPEAHQEAHAEBH@Z)
[build] osdCPU.lib(fvarLevel.cpp.obj) : error LNK2001: unresolved external symbol __std_find_trivial_4
[build] bin\Release\plugins\USDImporter.dll : fatal error LNK1120: 1 unresolved externals
```

Switching to `Windows-vs2022` preset seems to have same issue:
```bash
[build]   Generating Code...
[build]      Creating library C:/Users/Administrator/Projects/cool-mapping-project/Falcor/build/windows-vs2022/Source/plugins/importers/USDImporter/Debug/USDImporter.lib and object C:/Users/Administrator/Projects/cool-mapping-project/Falcor/build/windows-vs2022/Source/plugins/importers/USDImporter/Debug/USDImporter.exp
[build] osdCPU.lib(level.cpp.obj) : error LNK2019: unresolved external symbol __std_find_trivial_4 referenced in function "int * __cdecl std::_Find_unchecked<int *,int>(int *,int * const,int const &)" (??$_Find_unchecked@PEAHH@std@@YAPEAHPEAHQEAHAEBH@Z) [C:\Users\Administrator\Projects\cool-mapping-project\Falcor\build\windows-vs2022\Source\plugins\importers\USDImporter\USDImporter.vcxproj]
[build] osdCPU.lib(fvarLevel.cpp.obj) : error LNK2001: unresolved external symbol __std_find_trivial_4 [C:\Users\Administrator\Projects\cool-mapping-project\Falcor\build\windows-vs2022\Source\plugins\importers\USDImporter\USDImporter.vcxproj]
[build] C:\Users\Administrator\Projects\cool-mapping-project\Falcor\build\windows-vs2022\bin\Debug\plugins\USDImporter.dll : fatal error LNK1120: 1 unresolved externals
```

Any ideas or suggestions are appreciated.

**Comment by skallweitNV** [comment]
Is this a clean clone? Did you run `setup.bat` before building? Did you follow the README? It seems like you use an outdated version of the `falcor_dependencies` package, but maybe there is another issue.

**Comment by sHaol0w** [comment]
Hi,
Do you solve this issue? I have encountered the same problem. 

Additionally I have modified packman's archive7z.py file in order to solve a problem in setup_vs2022.bat's uncomressing.

**Comment by zheng95z** [comment]
Hi @sHaol0w  and @skallweitNV. I failed to solve it and went back to Falcor 5.2 eventually.

And yes this is a clean clone and I believe I followed the README exactly.

Before the clone and setup Falcor 6.0 I clean all packman package and dependencies of previous version of Falcor.

**Comment by sHaol0w** [comment]
Hi @zheng95z , I skipped this by using cmake flag (which is provided since 6.0) to skip USDimporter related compilation. That should work for 6.0 and 7.0. Maybe you can try hhhhhhh

**Comment by zheng95z** [comment]
> Hi @zheng95z , I skipped(but not solved) this error by using cmake flag (which is provided since 6.0) to skip USDimporter related compilation. That should work for 6.0 and 7.0. Maybe you can try hhhhhhh Thanks for your excellent project @skallweitNV and hope for some official solution on this little environment issue...

Hi @sHaol0w, thanks for the pointer!

I bypassed this issue by change this line of code in `CMakeLists.txt`:

```cmake
set(FALCOR_ENABLE_USD OFF CACHE BOOL "Enable USD")
```
