### ISSUE TITLE
use falcor as a python module

### ISSUE THREAD

**Issue by xiaoshux** [NVIDIAGameWorks/Falcor#388]
I know that the way falcor works is that falcor reads the pyscene file and the python script, and then performs rendering based on the python script. But I want to change it to falcor as a module that I call externally and keep the state after reading pyscene and python scripts. I can use renderFrame externally to control it frame by frame. Is there any solution?

**Comment by skallweitNV** [comment]
The next release will have lots of new bindings to run Falcor in Python, it's coming soon.
