### ISSUE TITLE
performance gap between windows and linux

### ISSUE THREAD

**Issue by GensokyoLover** [NVIDIAGameWorks/Falcor#405]
i tried to run testbed on linux and windows using vulkan,and found large performance gap.
```
def setup_renderpass(testbed):
    render_graph = testbed.create_render_graph("PathTracer")
    render_graph.create_pass("PathTracer", "PathTracer", {'samplesPerPixel': 1})
    render_graph.create_pass("GBufferRT", "GBufferRT", {'samplePattern': 'Stratified', 'sampleCount': 16, 'useAlphaTest': True})
    render_graph.create_pass("AccumulatePass", "AccumulatePass", {'enabled': True, 'precisionMode': 'Single'})
    render_graph.add_edge("GBufferRT.vbuffer", "PathTracer.vbuffer")
    render_graph.add_edge("GBufferRT.posW", "AccumulatePass.posW")
    render_graph.add_edge("GBufferRT.emissive", "AccumulatePass.emissive")
    render_graph.add_edge("GBufferRT.normW", "AccumulatePass.normW")
    render_graph.add_edge("GBufferRT.viewW", "AccumulatePass.viewW")
    render_graph.add_edge("GBufferRT.diffuseOpacity", "AccumulatePass.diffuseOpacity")
    render_graph.add_edge("GBufferRT.specRough", "AccumulatePass.specRough")
    render_graph.add_edge("PathTracer.color", "AccumulatePass.input")
    render_graph.mark_output("AccumulatePass.output")
    testbed.render_graph = render_graph
class FalcorVariableRenderer:
    def __init__(self, tonemap_type = "log1p",deviceType = falcor.DeviceType.Vulkan, deviceID = 0):
        self.device = falcor.Device(type=deviceType, gpu=deviceID)
        self.tonemap_type = tonemap_type
        self.width = 1920
        self.height = 1080
        self.resolution = falcor.uint2(1920,1080)
        self.startPosition = falcor.uint2(0,0)
        self.renderer = falcor.Testbed(width=self.width, height=self.height, position = self.startPosition,ow =self.resolution ,create_window=False, device=self.device)
        self.renderer.setSpp(400)
        self.scene = None
        self.integrator = None
        self.params = None
        self.variables_ids = None
        self.sensors = None
        self.emitters = None
        self.shapes = None
        self.shapegroups = None
        self.bsdfs = None
        self.initial_values = None
        self.variables = {}
        self.min_bounds = {}
        self.len_bounds = {}
        self.totalPara = 0
```
linux performance, gpu memory usage is only 500MB,and we need nearly 40S to render a 400spp 1920 * 1080 image
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/76512911/5cab71b1-2316-4265-8c59-f9952b143701)
windows performance，gpu memory usage is nearly 1.5 GB,and we need only 4S to render the same image
before running:
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/76512911/9614d7c5-dbf8-4410-9e16-4e98da71cc5f)
runtime
![image](https://github.com/NVIDIAGameWorks/Falcor/assets/76512911/64371030-c944-407c-b10b-f467661b0226)
Ii will profile it later and give more details

**Comment by GensokyoLover** [comment]
> i tried to run testbed on linux and windows using vulkan,and found large performance gap.
> 
> ```
> def setup_renderpass(testbed):
>     render_graph = testbed.create_render_graph("PathTracer")
>     render_graph.create_pass("PathTracer", "PathTracer", {'samplesPerPixel': 1})
>     render_graph.create_pass("GBufferRT", "GBufferRT", {'samplePattern': 'Stratified', 'sampleCount': 16, 'useAlphaTest': True})
>     render_graph.create_pass("AccumulatePass", "AccumulatePass", {'enabled': True, 'precisionMode': 'Single'})
>     render_graph.add_edge("GBufferRT.vbuffer", "PathTracer.vbuffer")
>     render_graph.add_edge("GBufferRT.posW", "AccumulatePass.posW")
>     render_graph.add_edge("GBufferRT.emissive", "AccumulatePass.emissive")
>     render_graph.add_edge("GBufferRT.normW", "AccumulatePass.normW")
>     render_graph.add_edge("GBufferRT.viewW", "AccumulatePass.viewW")
>     render_graph.add_edge("GBufferRT.diffuseOpacity", "AccumulatePass.diffuseOpacity")
>     render_graph.add_edge("GBufferRT.specRough", "AccumulatePass.specRough")
>     render_graph.add_edge("PathTracer.color", "AccumulatePass.input")
>     render_graph.mark_output("AccumulatePass.output")
>     testbed.render_graph = render_graph
> class FalcorVariableRenderer:
>     def __init__(self, tonemap_type = "log1p",deviceType = falcor.DeviceType.Vulkan, deviceID = 0):
>         self.device = falcor.Device(type=deviceType, gpu=deviceID)
>         self.tonemap_type = tonemap_type
>         self.width = 1920
>         self.height = 1080
>         self.resolution = falcor.uint2(1920,1080)
>         self.startPosition = falcor.uint2(0,0)
>         self.renderer = falcor.Testbed(width=self.width, height=self.height, position = self.startPosition,ow =self.resolution ,create_window=False, device=self.device)
>         self.renderer.setSpp(400)
>         self.scene = None
>         self.integrator = None
>         self.params = None
>         self.variables_ids = None
>         self.sensors = None
>         self.emitters = None
>         self.shapes = None
>         self.shapegroups = None
>         self.bsdfs = None
>         self.initial_values = None
>         self.variables = {}
>         self.min_bounds = {}
>         self.len_bounds = {}
>         self.totalPara = 0
> ```
> 
> linux performance, gpu memory usage is only 500MB,and we need nearly 40S to render a 400spp 1920 * 1080 image ![image](https://user-images.githubusercontent.com/76512911/285256112-5cab71b1-2316-4265-8c59-f9952b143701.png) windows performance，gpu memory usage is nearly 1.5 GB,and we need only 4S to render the same image before running: ![image](https://user-images.githubusercontent.com/76512911/285274105-9614d7c5-dbf8-4410-9e16-4e98da71cc5f.png) runtime ![image](https://user-images.githubusercontent.com/76512911/285274285-64371030-c944-407c-b10b-f467661b0226.png) Ii will profile it later and give more details
GPU on linux is A6000 and the other is 4090

**Comment by saada2006** [comment]
How did you get GBufferRT to run on Linux? I keep getting an error saying ROVs are not supported.
