### ISSUE TITLE
Failed to fetch dependencies

### ISSUE THREAD

**Issue by yarusophialiu** [NVIDIAGameWorks/Falcor#411]
when running setup_vs2022.bat, I encountered this 403 error.
![error](https://github.com/NVIDIAGameWorks/Falcor/assets/22484647/aead516f-d924-4d2b-aad3-add718afe338)

It fails to fetch the package.

**Comment by DDHnd** [comment]
i got this too when i check out **a commit not the newest**.seem like this server not have the source i request

**Comment by skallweitNV** [comment]
The issue is that earlier version of `packman`, the utility we use to fetch dependencies, doesn't work anymore. So you should either use the latest `master` or copy the `tools/packman` folder from latest `master` to your local clone.
