### ISSUE TITLE
Couldn't find ForwardRenderer.py

### ISSUE THREAD

**Issue by Thomaswang0822** [NVIDIAGameWorks/Falcor#416]
I am following the tutorials, but I couldn't find the script given in [this section](https://github.com/NVIDIAGameWorks/Falcor/blob/master/docs/tutorials/01-mogwai-usage.md#loading-a-script-py)

It seems like there isn't a Data/ under Source/Mogwai

**Comment by skallweitNV** [comment]
The documentation is outdated, sorry for that. The forward rendering passes have been removed.

**Comment by Thomaswang0822** [comment]
Ok, thanks for this. I just replace it with some existing script like PathTracer.py and it works.

**Comment by bipul-mohanto** [comment]
So, instead of the `Source/Mogwai/Data/`, the scripts are now in `\tests\image_tests\renderpasses\graphs`? All scripts?

**Comment by Thomaswang0822** [comment]
But still `ForwardRenderer.py` is not there. My guess is it's renamed to `PathTracer.py` or `MinimalPathTracer.py` in a major version update.

**Comment by bipul-mohanto** [comment]
My bad, I am also a beginner in Falcor. I guess, forward rendering and path tracing are not the same, and the `ForwardRenderer.py` has been deprecated. But still, I am confused as to why the scripts are in two different folders. e.g.,  under `Falcor/tests/image_tests/renderpasses/graphs`, and `Falcor/scripts`!
