### ISSUE TITLE
Dependencies for old releases (e.g., 5.2)

### ISSUE THREAD

**Issue by hchoi405** [NVIDIAGameWorks/Falcor#417]
First of all, thank you all for maintaining this wonderful project.

I was working on old version 5.2 but suddenly, it didn't build due to missing dependencies from packman.

How can I get the binaries (zips) of dependencies for old releases?

Thank you for reading.

**Comment by skallweitNV** [comment]
You'd have to update the `packman` package manager in the old version. Just copy the `tools/packman` folder from `master` to your local clone. That might work.

**Comment by hchoi405** [comment]
Thank you for the answer! It's perfectly working now!
