### ISSUE TITLE
Vulkan samples crash when a 1920x1080 window can't be created

### ISSUE THREAD

**Issue by tfoleyNV** [NVIDIAGameWorks/Falcor#42]
I often run Falcor on a screen that is only 1920x1080, and as a result all of my Falcor windows get created at a size slightly smaller than that. This seems to not cause problems on D3D12 (at least not any more), but when running with Vulkan I get errors and can't run the samples.

**Comment by nbenty** [comment]
@kyaoNV if this is fixed please close it
