### ISSUE TITLE
How to define camera movements(animation) in pyscene?

### ISSUE THREAD

**Issue by ychanu** [NVIDIAGameWorks/Falcor#428]
Hello, 

I'm new to Falcor and have a question regarding camera movements in pbrt scenes.

I've been looking for tutorials on this topic but haven't been successful in finding any relevant guides.
I was wondering if it's possible to pre-define camera movements using pyscene. (import pbrt scene)
Anyone knows related example codes?

Thank you for your assistance.

**Comment by guiqi134** [comment]
I think it's possible. Basically, you can look into the `sceneBuilder.createAnimation()` and `Animation` class under Scripts document. 

Here is an example how you can define a linear camera movement from a start point to an end point:
```
# Add camera2 
camera2 = Camera("Camera2")
camera2.position = float3(-5.190841, 3.900723, 20.509645)
camera2.target = float3(-5.501971, 3.859276, 19.560183)
camera2.up = float3(0.000000, 1.000000, 0.000000)
camera2.focalLength = 35
camera2.focalDistance = 1000.0
camera2.apertureRadius = 0.0
sceneBuilder.addCamera(camera2)

# Add camera 2 animation
cameraDuration = 10 # in seconds 
cameraAnimation = sceneBuilder.createAnimation(camera2, "Camera2 Animation", cameraDuration)
tf_start = Transform()
tf_start.lookAt(camera2.position, camera2.target, camera2.up)
tf_end = Transform()
tf_end.lookAt(
    float3(-8.160987, 3.505056, 11.445773),
    float3(-8.472117, 3.463609, 10.496310),
    float3(0.000000, 1.000000, 0.000000)
)
cameraAnimation.addKeyframe(0, tf_start)
cameraAnimation.addKeyframe(cameraDuration, tf_end)
```

**Comment by ychanu** [comment]
@guiqi134 
Thanks to you, succeeded basic camera animation!
It has been really helpful.

I will refer to the code you provided and study documents further :)
