### ISSUE TITLE
Vulkan validation layer errors when running most samples

### ISSUE THREAD

**Issue by tfoleyNV** [NVIDIAGameWorks/Falcor#43]
With pretty much any sample I run under `DebugVK`, I get a bunch of spew to the debug log of the form:

```
FalcorVK Error: You must call vkBeginCommandBuffer() before this call to ...
```

There are other validation-layer messages, but these are the main annoyance. This makes it harder for me to notice when I introduce new errors into a sample, and also makes it less useful to place a breakpoint on the error logging to diagnose my own errors (I need to skip a bunch of these pre-existing errors before getting to mine).

Ideally the samples should all run without validation errors, since there might be some platforms where those validation issues result in instability.

**Comment by nbenty** [comment]
@kyaoNV If this is fixed, please close it
