### ISSUE TITLE
How to capture video? (after v6)

### ISSUE THREAD

**Issue by ychanu** [NVIDIAGameWorks/Falcor#432]
Hello,

I attempted to capture my animation video using "m.videoCapture." 
However, it appears to have been removed in versions following 6. 
Could you advise me on how to capture video in Falcor 7?

Thank you.

**Comment by ychanu** [comment]
I solved this, using frameCapture :)

**Comment by tyouthfor** [comment]
> I solved this, using frameCapture :)

Hi, could you please share an example of how to capture a video using frameCapture?
