### ISSUE TITLE
FPS counter in demo incorrect / negative GPU times reported.

### ISSUE THREAD

**Issue by stolk** [NVIDIAGameWorks/Falcor#49]
If I run the NormalMapFiltering demo from Falcor, it launches zoomed out, and claims 240fps.

If I zoom in on the face, the FPS completely breaks down.
I estimate to roughly 3 frames per second.

Yet, the FPS counter claims it runs at 30 fps, which is not correct.

See this video to observer the issue:
https://vimeo.com/260673177

Ubuntu 16.04.4 LTS
OpenGL renderer string: GeForce GTX 750 Ti/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 384.111

**Comment by stolk** [comment]
This may be related:

If I press the 'p' key, I get more timing stats.
However, some of those times go negative, which does not make any sense.

![image](https://user-images.githubusercontent.com/455280/37571880-ec1aa7aa-2abf-11e8-8463-1abf87fe1de1.png)

**Comment by nbenty** [comment]
Is this on Linux?

**Comment by stolk** [comment]
Yes

**Comment by nbenty** [comment]
@kyaoNV Please fix it for 3.0. Also, time to figure out where the wireframe is coming from

**Comment by kyaoNV** [comment]
Fixed in `dev-3.0.3`
