### ISSUE TITLE
Info about DirectX raytracing support..

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Falcor#50]
I have read Falcor is working on DXR support and as you seem to be working on version 3 currently asking if it will be ready by that version release or a new branch will be created in the meanwhile to test.. thanks..

**Comment by nbenty** [comment]
DXR support is part of Falcor 3.0, which will be released on April 10th.
It will be added to the `dev-3.0` branch early next week.

**Comment by oscarbg** [comment]
Thanks for detailed info..
seems a great start of open source jointly with also new DXR tutorials..

**Comment by nbenty** [comment]
You can find the DXR support in `dev_dxr` branch
