### ISSUE TITLE
Falcor build failed with VS 2015

### ISSUE THREAD

**Issue by SirKnightTG** [NVIDIAGameWorks/Falcor#53]
Using a fresh clone of Falcor and VS 2015 I am seeing the following build errors:

1>  Package successfully installed to D:\packman-repo\chk\vulkansdk\1.0.51.0
1>  Package 'slang' at version '0.9.5' is missing from local storage.
1>  Traceback (most recent call last):
1>    File "D:\packman-repo\packman-common\5.1\packman.py", line 967, in <module>
1>      main()
1>    File "D:\packman-repo\packman-common\5.1\packman.py", line 948, in main
1>      return args.func(**vars(args))
1>    File "D:\packman-repo\packman-common\5.1\packman.py", line 419, in pull_cmd
1>      variable_file)
1>    File "D:\packman-repo\packman-common\5.1\packman.py", line 453, in pull_with_variable_file
1>      pull_dependencies(deps, remote_configs, remote_names, platform, postscript, variable_file)
1>    File "D:\packman-repo\packman-common\5.1\packman.py", line 528, in pull_dependencies
1>      package_path = tp[remote_name].get_package_path(package_name, package_version)
1>    File "D:\packman-repo\packman-common\5.1\transport\httptransport.py", line 35, in get_package_path
1>      if self.is_file_found(path):
1>    File "D:\packman-repo\packman-common\5.1\transport\httptransport.py", line 25, in is_file_found
1>      r = requests.head(protocol_and_path)
1>    File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\api.py", line 95, in head
1>      return request('head', url, **kwargs)
1>    File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\api.py", line 50, in request
1>      response = session.request(method=method, url=url, **kwargs)
1>    File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\sessions.py", line 465, in request
1>      resp = self.send(prep, **send_kwargs)
1>    File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\sessions.py", line 573, in send
1>      r = adapter.send(request, **kwargs)
1>    File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\adapters.py", line 431, in send
1>      raise SSLError(e, request=request)
1>  botocore.vendored.requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "call D:\Programming\Falcor\Framework\Source\\..\BuildScripts\prebuild.bat D:\Programming\Falcor\Framework\Source\\..\ D:\Programming\Falcor\ D:\Programming\Falcor\Framework\Source\ x64 x64 DebugD3D12 D:\Programming\Falcor\Bin\Int\x64\DebugD3D12\Lib\
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073:
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code 1.

Then later on:

9>------ Rebuild All started: Project: ModelViewer, Configuration: Debug x64 ------
2>  Shadows.cpp
5>  ShaderBuffers.cpp
3>  MultiPassPostProcess.cpp
7>  SimpleDeferred.cpp
4>  ProjectTemplate.cpp
9>  ModelViewer.cpp
6>  ShaderToy.cpp
8>  StereoRendering.cpp
5>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
2>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
6>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
3>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
8>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
10>------ Rebuild All started: Project: SceneEditor, Configuration: Debug x64 ------
7>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
9>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory
11>------ Rebuild All started: Project: EnvMap, Configuration: Debug x64 ------
12>------ Rebuild All started: Project: NormalMapFiltering, Configuration: Debug x64 ------
4>d:\programming\falcor\framework\source\graphics\program\programreflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory

**Comment by nbenty** [comment]
Fixed in `dev-3.0` branch. We will merge it into `master` soon.
