### ISSUE TITLE
UpdateDependencies -  error when downloading Slang

### ISSUE THREAD

**Issue by dsanjit** [NVIDIAGameWorks/Falcor#54]
When building I get the following error:
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

This seems to occur when UpdateDependencies.bat tries to get Slang. I had to comment out the dependency and manually download the release to compile.

**Comment by nbenty** [comment]
This issue is fixed in `dev-3.0` branch. We will merge that fix into `master` soon. In any case, I suggest you use that branch.
