### ISSUE TITLE
Complains about missing external slang on windows

### ISSUE THREAD

**Issue by Atrix256** [NVIDIAGameWorks/Falcor#61]
I downloaded Falcor, opened in vs 2017 (not 2015, is that ok?) and when i compile it complains about slang missing.

None of the projects build because they error on the missing file
2>d:\github\falcor\framework\source\Graphics/Program/ProgramReflection.h(32): fatal error C1083: Cannot open include file: 'Externals/Slang/slang.h': No such file or directory

Please let me know if there's any more information I can provide.

I'm going to try to work around it but figured i should report it as this is not listed in windows prerequisites or anywhere else that i can find.

alan.wolfe@gmail.com
https://twitter.com/Atrix256

1>------ Build started: Project: Falcor, Configuration: ReleaseD3D12 x64 ------
1>Processing project file 'D:\github\Falcor\dependencies.xml'
1>Package 'slang' at version '0.9.5' is missing from local storage.
1>Traceback (most recent call last):
1>  File "D:\packman-repo\packman-common\5.1\packman.py", line 967, in <module>
1>    main()
1>  File "D:\packman-repo\packman-common\5.1\packman.py", line 948, in main
1>    return args.func(**vars(args))
1>  File "D:\packman-repo\packman-common\5.1\packman.py", line 419, in pull_cmd
1>    variable_file)
1>  File "D:\packman-repo\packman-common\5.1\packman.py", line 453, in pull_with_variable_file
1>    pull_dependencies(deps, remote_configs, remote_names, platform, postscript, variable_file)
1>  File "D:\packman-repo\packman-common\5.1\packman.py", line 528, in pull_dependencies
1>    package_path = tp[remote_name].get_package_path(package_name, package_version)
1>  File "D:\packman-repo\packman-common\5.1\transport\httptransport.py", line 35, in get_package_path
1>    if self.is_file_found(path):
1>  File "D:\packman-repo\packman-common\5.1\transport\httptransport.py", line 25, in is_file_found
1>    r = requests.head(protocol_and_path)
1>  File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\api.py", line 95, in head
1>    return request('head', url, **kwargs)
1>  File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\api.py", line 50, in request
1>    response = session.request(method=method, url=url, **kwargs)
1>  File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\sessions.py", line 465, in request
1>    resp = self.send(prep, **send_kwargs)
1>  File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\sessions.py", line 573, in send
1>    r = adapter.send(request, **kwargs)
1>  File "D:\packman-repo\packman-common\5.1\site-packages\botocore-1.7.3\botocore\vendored\requests\adapters.py", line 431, in send
1>    raise SSLError(e, request=request)
1>botocore.vendored.requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "call D:\github\Falcor\Framework\Source\\..\BuildScripts\prebuild.bat D:\github\Falcor\Framework\Source\\..\ D:\github\Falcor\ D:\github\Falcor\Framework\Source\ x64 x64 ReleaseD3D12 D:\github\Falcor\Bin\Int\x64\ReleaseD3D12\Lib\
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073:       
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "Falcor.vcxproj" -- FAILED.

**Comment by Atrix256** [comment]
That branch does indeed fix the problem, thanks!

**Comment by kyaoNV** [comment]
The relevant commit has been merged into `master`

**Comment by Nolram12345** [comment]
This issue seems to have occurred again - at least I have been noticing it in this repository : https://github.com/DQLin/ReSTIR_PT
