### ISSUE TITLE
Empty sample project taking almost 3 GB of memory in DX12

### ISSUE THREAD

**Issue by Alekssasho** [NVIDIAGameWorks/Falcor#63]
When creating new Device you create a QueryHeap for the GPUTimers with very large count of 128 * 1024 * 1024.
This is happening on this line https://github.com/NVIDIAGameWorks/Falcor/blob/master/Framework/Source/API/Device.cpp#L84.
This is allocating enormous amount of memory.

This seems unnecessary large and should be either lowered or made a constant that can be user changed for example in Device::Desc

**Comment by nbenty** [comment]
I assume you're running Vulkan. The DX12 backend only consumes 130MB.

We will fix it for the next release - add options to control the number of GPU queries and the sizes of the descriptor heaps.

**Comment by Alekssasho** [comment]
Actually it is both Dx12 and Vulkan. The number you are passing is the count of slots, but every query slot is taking more than 1 byte, so is both Vulkan and Dx12 this is a lot more than 128 MB.

**Comment by nbenty** [comment]
I changed the number to 50000. I'm replacing this issue with #69
