### ISSUE TITLE
don't update dependencies

### ISSUE THREAD

**Issue by GermanAizek** [NVIDIAGameWorks/Falcor#64]
error connection aborted.
 `File "X:\packman-repo\packman-common\5.2.4\site-packages\s3transfer-0.1.11\s3transfer\futures.py", line 233, in result
    raise self._exception
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', error(10061, '\xcf\xee\xe4\xea\xeb\xfe\xf7\xe5\xed\xe8\xe5 \xed\xe5 \xf3\xf1\xf2\xe0\xed\xee\xe2\xeb\xe5\xed\xee,'))`

**Comment by nbenty** [comment]
It works for me on Windows 10.
What OS are you using? Which branch?

**Comment by nbenty** [comment]
I can't reproduce it. I tried 3 different machines on 2 different networks.

@halldorfannar Do you have any idea what might go wrong?

**Comment by GermanAizek** [comment]
You can close the downloaded file on another network and compile it.
