### ISSUE TITLE
Compile error when Windows language is Chinese

### ISSUE THREAD

**Issue by csyonghe** [NVIDIAGameWorks/Falcor#67]
I am using Windows 10 with my OS code page set to 936. When compiling Falcor I got the following error message from msvc:

>d:\git_repo\falcornv\falcor\framework\externals\ffmpeg\include\libavutil\rational.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss (compiling source file Utils\Video\VideoEncoder.cpp)

Because treat warnings as errors is turned on, I cannot get Falcor to compile due to this error message. Save the file as UTF8 does not solve the issue, and I cannot locate the offending characater in rational.h.

The workaround is to suppress warning 4819 in project settings. (using pragma in rational.h does not work)

**Comment by nbenty** [comment]
That error is from an external dependency. We will investigate.
@kyaoNV , this one is yours

**Comment by kyaoNV** [comment]
This is an issue from FFMPEG, we can't do anything about it.
