### ISSUE TITLE
Again problem with update_dependencies

### ISSUE THREAD

**Issue by GermanAizek** [NVIDIAGameWorks/Falcor#71]
To lay the project on the second pc and again problems with update_dependencies.bat
I understand by mistake, he did not find glm and I need to separately shake and include it?

`H:\GIT\FalcorTest\Falcor>update_dependencies.bat
Processing project file 'H:\GIT\FalcorTest\Falcor\dependencies.xml'
Package 'glm' at version '0.9.8.5' is missing from local storage.
packman(ERROR): Package not found on specified remote servers!`

**Comment by nbenty** [comment]
It works for me (latest `master`).

IIRC last time you had issues with the network no connecting to S3. Are you sure the connection work properly now?

**Comment by halldorfannar** [comment]
We have a workaround for this problem.  It's actually due to S3 authentication failure which can happen on certain machine configurations.  Anyway, I will create a merge request this week to work around the problem.

**Comment by GermanAizek** [comment]
Okay, try to collect other branches.

**Comment by GermanAizek** [comment]
Noticed some problems with prebuild.bat, or more precisely, the call returns 1 and as a result the project does not compile.

**Comment by GermanAizek** [comment]
@halldorfannar @nbenty 
I'm very stupid XD The solution to the problem was very simple! I had a real time on the computer for 16 minutes and apparently the synchronization did not go through the S3 servers. Leave the solution to the problem in the FAQ to not create more discussions.
