### ISSUE TITLE
Shader with atomic intrinsics function failed to compile

### ISSUE THREAD

**Issue by guoxx** [NVIDIAGameWorks/Falcor#73]
Shader that use atomic intrinsics function failed to compile.
Here are a example of the code.
```
#define NUM_THREADS_ 256

groupshared uint gs_data[NUM_THREADS_];

[numthreads(NUM_THREADS_, 1, 1)]
void main(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint origValue;
    InterlockedAdd(gs_data[dispatchThreadID.x], 1u, origValue);
}
```

Code processed by slangc
```

static groupshared uint  _SV07gs_data[256];

[numthreads(256, 1, 1)]
void main(vector<uint,3> _S1 : SV_DISPATCHTHREADID)
{
    uint _S2 = _S1.x;
    uint _S3;
    uint _S4 = (_SV07gs_data[_S2]);
    _S3 = _S4;
    uint _S5;
    InterlockedAdd(_S3, (1), _S5);
    uint _S6 = _S3;
    (_SV07gs_data[_S2]) = _S6;
    uint _S7 = _S5;
    return;
}
```

It's obvious that **_S3** is not a groupshared variable or UAV.  

Also there are some issue with slang I met before, do you guys think is it possible to provide some workaround solution instead of waiting the fix from slang?

**Comment by nbenty** [comment]
@tfoleyNV FYI.

@guoxx as long as you are using raw-HLSL shaders with explicit resource bindings, I can add a compilation flag which will bypass Slang. The downside is that you won't be able to use the material system in those shaders. It's memorial day, so it will take a day or two before I implement it.

**Comment by guoxx** [comment]
@nbenty that would be great.

**Comment by tfoleyNV** [comment]
@guoxx Slang 0.10.20 is now live. Please try if when you get a chance and let me know if if resolves the problem.

**Comment by guoxx** [comment]
@tfoleyNV it works. Thanks all you guys for the impressive work.
