### ISSUE TITLE
Update Subresource like( D3D11_BOX))

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#75]
I have a question. May I update part of texture like  D3D11_BOX in Directx 11?
or can I create a reserved resource in Falcor?
I searched for this kind of function, but haven't found.
Thanks!

**Comment by nbenty** [comment]
No, but that should be easy to implement.

Do you want to upload new data from the CPU or just copy part of an existing texture similar to DX11's `CopySubresourceRegion`?

**Comment by bryan05** [comment]
Yes, thank you for your answer.

**Comment by nbenty** [comment]
That doesn't answer my question :)
Do you want to (1) upload new data from the CPU; or (2) copy a part of a texture?

**Comment by bryan05** [comment]
sorry.
I want upload new data from the cpu, but only part of the data. not like   void Texture::uploadInitData(const void* pData, bool autoGenMips), which upload all the data from cpu

**Comment by bryan05** [comment]
later I want to implement terrain system with Falcor, I think in that case, part of texture will be copied.

**Comment by nbenty** [comment]
OK, that should be straightforward to add. We'll add it to the 3.0.4 release todo list

**Comment by bryan05** [comment]
thanks

**Comment by nbenty** [comment]
@bryan05 Do you still need it?

**Comment by bryan05** [comment]
yes sure, I think it will be added to 3.0.4, so I closed it

**Comment by nbenty** [comment]
Cool. Just wanted to double-check

**Comment by nbenty** [comment]
Added `CopyContext::copySubresourceRegion()` and `CopyContext::updateSubresourceData()` to branch `dev-3.0.4`
