### ISSUE TITLE
no GraphicsProgram::createFromString in master branch

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#77]
my program uses branch 3.0 and needs to preprocess the shader file. So I need to load shader file first , preprocess them and then pass the preprocessed shader to GraphicsProgram::createFromString. But now the function is removed in the master branch.

**Comment by nbenty** [comment]
OK, I'll add it

**Comment by bryan05** [comment]
thank you very much

**Comment by nbenty** [comment]
Added in `dev-3.0.4`.
I opted not to add `createFromString`. You'll need to use `GraphicsProgram::create(Desc& d)` instead.
It should look like:
```
GraphicsProgram::Desc d;
d.addShaderString("this is a shader").psEntry("ps").vsEntry("vs");
pProgram = GraphicsProgram::create(d);
```

**Comment by bryan05** [comment]
thanks a lot. another question? can I add different string for vertex shader and pixel shader? I looked through Program.cpp. it seems like all the shader (vertex,pixel, geometry, domain) code must be stored in the same string?

**Comment by nbenty** [comment]
`d.addShaderString("psstring").psEntry("ps").addShaderString("vsstring").vsEntry("vs");`

You can multiple strings and filenames

**Comment by tfoleyNV** [comment]
Based on what I remember, `Program::Desc` suppprts multiple source files/strings. Any `vsEntry` etc. call should implicitly use the source file/string you last added.

**Comment by bryan05** [comment]
great!
