### ISSUE TITLE
DXR fallback layer integration

### ISSUE THREAD

**Issue by tankiJong** [NVIDIAGameWorks/Falcor#83]
Hi,

I am wondering if there is any plan to integrate DXR fallback layer into the engine?
Since I am doing some work based on Falcor, where I will possibly integrate fallback layer for myself anyway, I am wondering does team accept public contribution?

If you do, is there any contribution guide or coding standard? I can submit PR after I have done the work.

Thank you in advance :)

**Comment by kyaoNV** [comment]
We indeed welcome contributions through pull requests! You can find coding conventions in `Framework/Documentation/CodeConvention.cpp`.

@nbenty would be able to tell you more about DXR plans.

**Comment by johannesugb** [comment]
Any news/progress on this topic?
I'm thinking about contributing, too. But I'd like to avoid spending time on this, if it is already almost done or so.

**Comment by nbenty** [comment]
We are not actively working on it.
The current fallback layer API has too many differences compared to the actual DXR spec. We have no plans to support it unless there will be a fallback layer which better matches the API.
