### ISSUE TITLE
update texture with offset x and offset y

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#85]
right now there is Buffer::updateData, but there is no such function in Texture class. 
By the way in the Buffer::updateData there is only one offset. Can you please provide a function, which can update the texture from (offset x, offset y) with size (width, height)?

I can do this and upload the source if you don't have time.

**Comment by nbenty** [comment]
`CopyContext::updateSubresourceData()` does what you're looking for
