### ISSUE TITLE
warning by  calling clearFbo

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#88]
when I call clearFbo with following arguments
`RenderContext()->clearFbo(contex->getGraphicsState()->getFbo().get(), glm::vec4(0), 1.0f, 0,  Falcor::FboAttachmentType::Depth| Falcor::FboAttachmentType::Stencil);`

I got the warning in every frame rendering:
D3D12 WARNING: ID3D12CommandList::ClearDepthStencilView: The application did not pass any clear value to resource creation. The clear operation is typically slower as a result; but will still clear to the desired value. [ EXECUTION WARNING #821: CLEARDEPTHSTENCILVIEW_MISMATCHINGCLEARVALUE]

**Comment by nbenty** [comment]
It's not a bug, it's just an annoying perf warning message.
@kyaoNV Please filter that message

**Comment by bryan05** [comment]
thanks for letting me know.
