### ISSUE TITLE
Populating an array of Texture2D by including mipmaps.

### ISSUE THREAD

**Issue by k3dexp** [NVIDIAGameWorks/Falcor#91]
First of all, thank you for the project. I find it incredibly useful for quickly trying out ideas and seeing the results almost instantly. 

I've been trying to implement bindless texturing with Falcor by placing all the textures into an array of Texture2D but no matter what I tried I could not get the textures after the first one upload properly. I get no messages from the debugging layer during the upload operation but when I access the textures from the pixel shader, with the exception of the first texture in the array, they are all blank.

Is it actually feasible to achieve this with Falcor in its current state? If it is, do you have a working example of how to achieve this, or do you have any guidance you could share?

**Comment by nbenty** [comment]
Yes, that should work, I've tried it before.
Also, the material system uses an array of textures and it works correctly.

Can you post you shader code (at least the declarations section) and how you bind the textures from C++?

**Comment by k3dexp** [comment]
This issue has been resolved after the latest changes in 3.0.5.

I was using exactly the same method you use in the LeanMap effect but it wasn't working for me.

Glad to see that you are constantly making improvements to the system, which in this case also solved the issue I was having.
