### ISSUE TITLE
Integration of other GameWorks technologies.

### ISSUE THREAD

**Issue by k3dexp** [NVIDIAGameWorks/Falcor#93]
In one of the presentations I've watched, you mention that you are planning to integrate VXGI and other GameWorks technologies into Falcor. Is there any development in this regard or is this a rather long term goal?

I personally would very much love to see VXGI and PhysX integrations happening.

**Comment by nbenty** [comment]
I plan to start working on it around September

**Comment by FishOrBear** [comment]
What does it look like now
