### ISSUE TITLE
GLM compile fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by udnaan** [NVIDIAGameWorks/Falcor#96]
The reason it fails is because g++ 7.3 is not a known compiler for the GLM version that packman downloads (0.9.8.5). It seems to be fixed in the [latest ](https://github.com/g-truc/glm/blob/master/glm/simd/platform.h#L75)
Overwriting the file from link above can be used as a temporary workaround. Overall, the GLM should be updated to a version that doesn't explicitly checks for GCC minor version to fix it.
Someone with a bit more time can look [here](https://github.com/g-truc/glm/commits/master/glm/simd/platform.h) to figure this out.

**Comment by nbenty** [comment]
@kyaoNV We need to upgrade all the libraries to the latest for Falcor 3.1

**Comment by kyaoNV** [comment]
The libraries will be updated today on the `dev-3.1` branch, and we will move to officially supporting Ubuntu 18.04 as the main Linux development version soon.

**Comment by kyaoNV** [comment]
Falcor 3.1 has updated GLM to 0.9.9.2.
