### ISSUE TITLE
INVALID_SUBRESOURCE_STATE

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#98]
I first create a vertex buffer
```
	vertex_buffer = Falcor::FBuffer::create(vbSize, Falcor::FBuffer::BindFlags::Vertex, Falcor::FBuffer::CpuAccess::Read, (void*)vertex.get());

	vertex_buffer->setName("vertex_screen_buffer");
		Falcor::Vao::BufferVec buffers{ vertex_buffer };
		mpVao = Falcor::Vao::create(Falcor::Vao::Topology::TriangleList, input_layout, buffers, indices_buffer, Falcor::ResourceFormat::R32Uint);
```
then I draw 
```
	pState->setVao(mpVao);
	getRenderContext()->drawIndexed(s.num_indices, s.indices_offset, s.vertex_offset + s.num_vertex * target);
```
for the first frame an error popped up

> D3D12 ERROR: ID3D12CommandList::DrawInstanced: Resource state (0x400: D3D12_RESOURCE_STATE_COPY_DEST) (assumed at first use) of resource (0x00000159998E4750:'**vertex_screen_buffer**') (subresource: 0) is invalid for use as a vertex buffer.  Expected State Bits (all): 0x1: D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER, Assumed Actual State: 0x400: D3D12_RESOURCE_STATE_COPY_DEST, Missing State: 0x1: D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]

after the first frame this error disappeared.  As you can see that **vertex_screen_buffer** is indeed a vertex buffer, how can it be set to state D3D12_RESOURCE_STATE_COPY_DEST. I also debugged and found that the **vertex_screen_buffer** is in state D3D12_RESOURCE_STATE_COMMON.

**Comment by nbenty** [comment]
You can't create a vertex-buffer on the readback heap.
This - `Falcor::FBuffer::CpuAccess::Read` - tells Falcor that the CPU will read from the buffer, so Falcor allocates it on the readback heap. Change it to `Write` (or better yet, `None` for better perf).

**Comment by bryan05** [comment]
thanks, the problem is solved
